### ISSUE TITLE
Consistency in printing messages

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1072]
Working through Makeflow, I notice that we have several different streams that information goes out through for Makeflow. For example we use fatal, printf, fprintf to stderr, and debug all in makeflow.c. Should we route the printf and fprintf calls through the debug library?

Also, should we have D_Notice, D_Error, and D_Fatal print to both the log and stderr? I believe currently they will print regardless of if we have a log specified, but if a log is specified I think we only print it to the log. Thoughts?

**Comment by dthain** [comment]
The code probably isn't as consistent as it could be, but there are good reasons to use each one.  The is the general convention across all of our code:

- stdout is for the ordinary output of a program, showing a modest amount of high level progress information that the user expects to see all of the time.  e.g. checking the dag, submitting jobs, dag overall succeeded or failed.
- stderr is specifically for error messages like the dag is unreadable, jobs could not be submitted, and so forth.  Ordinary errors enountered at the top level of makeflow should use stderr.  Unix distinguishes between stdout and stderr  so that `command > output` will send ordinary output to a file, while still showing error conditions on the console.
- debug is primarily for developers and troubleshooting of the underlying details, which may change considerably from release to release. e.g. We turn on debug to understand why a task fails when submitted to a specific work.
- fatal is for the limited use case of errors deep within our libraries that have no reasonable error return or prospects for recovery.  It's not a very user-friendly sort of exit and should be thought of as one level of severity short of a segmentation fault.

**Comment by btovar** [comment]
Nick and I were thinking of two issues regarding the debug log:

- Messages to stderr are not printed to the log, which would be nice for debugging purposes. We would like to use D_NOTICE everywhere we use stderr, with D_NOTICE printing both to the the debug log, and to stderr (only if the debug log is not being printed to stderr).

- Fatal messages are printed to the log, but not to stderr. We think they should print to both (if different).

**Comment by dthain** [comment]
I think those are good ideas.  I'll just suggest that only the log file have the date, time, and process header, otherwise the user-visible message would be lost in the clutter.

**Comment by btovar** [comment]
Fixed by #1124
