### ISSUE TITLE
Makeflow ignores return value of work_queue_task_specify_file

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1142]
Example:

output: /my/absolute/path
    ....

Work queue work_queue_task_specify_file prints an error on encountering the absolute path, and does not add the file to the task. Makeflow does not check for this and continues. The task only succeeds if the absolute path is globally accessible (e.g. afs).

Proposal: Any errors from work_queue_task_specify_file should be fatal to makeflow.

@nhazekam, @dthain: thoughts?

**Comment by nhazekam** [comment]
Would this check be better handled in makeflow_check_batch_consistency? This would force us to note when a file is specified as an absolute path but then we could decide it it is supported as a whole for each batch system as opposed to just Work Queue. makeflow_check_batch_consistency is where we currently check for remote renaming support.

**Comment by btovar** [comment]
I think now you know the code better... I have a present for you!

**Comment by btovar** [comment]
Checking in makeflow_check_batch_consistency should be ok, but note that this is in addition to that. work_queue_specify_file may fail in other ways.

**Comment by btovar** [comment]
After talking with @nhazekam:

1) makeflow will produce a notice for the absolute paths in work queue, as we do for remote renaming for other batch systems.
2) makeflow will produce a fatal exit on work_queue_specify_file.

**Comment by nhazekam** [comment]
Resolved in the referenced pull request. 

Solution: 
Batch_job* now has a feature to express whether absolute paths are allowed in a rule or not. 
If not allowed, Makeflow prevents rules from being executed in that queue if they have a remote absolute path.
Work Queue now produces a fatal error if an absolute path is incorrectly used, instead of printing to stderr, but continuing with computation.

Does not change all WQ errors in specify file to fatal.
