### ISSUE TITLE
condor transfer output files outside wq control

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1336]
As observed by @annawoodard.

A process is writing outside the task directory, at _CONDOR_SCRATCH_DIR. When the worker disconnects, condor transfer back that file. Some of those files are above 150GB, which were filling /tmp at the submission site.

Two solutions:

a) Specify transfer_output_files =""  ,  which disables the automatic transfer.  Before condor 7.9 it creates a file named "" at the submission site (as discussed here: 
https://www-auth.cs.wisc.edu/lists/htcondor-users/2013-January/msg00045.shtml ).

b) The worker removes any file at _CONDOR_SCRATCH_DIR as part of its cleanup.

@dthain?

**Comment by annawoodard** [comment]
Wouldn't a) be preferable, in case cleanup is interrupted somehow?

**Comment by btovar** [comment]
It is, the problem is that it does not work with all versions of condor. We can add a if then at the submit file, though.

**Comment by dthain** [comment]
To clarify, is the problem that that *worker* is creating output in `$_CONDOR_SCRATCH_DIR` (e.g. cache dir and such) or that the *tasks* are doing so?

**Comment by btovar** [comment]
The tasks.

**Comment by dthain** [comment]
Ok, it sounds like you are trying to solve the problem that the worker has some files that you don't want brought back.  But, the bigger problem is that the task is writing outside of its permitted area at the worker, which is going to cause storage problems there as well.  I suggest that you try to stop it at that side, if possible.

In principle, the worker should run at a different privilege level than the task.  In practice, we can't do that.  So, some possible workarounds:

a) The worker could `chmod 500` its working directory, and then manually change the permissions only to create the task and cache directories.  That should stop tasks from writing where they shouldn't, unless they are *really* insistent. 

b) The worker could set `CONDOR_SCRATCH_DIR`, `TEMPDIR` and so forth independently for each task, so that they are encouraged to write into their own directories, instead of that of the whole worker.

c) Figure out what else is inducing the task to write to that directory, and change it...?

**Comment by matz-e** [comment]
In this case, we save command output temporarily by re-directing it to a file created in python via
```
tempfile.mkstemp()
```
From the [documentation](https://docs.python.org/2/library/tempfile.html#tempfile.mkstemp):
> ` tempfile.mkstemp([suffix=''[, prefix='tmp'[, dir=None[, text=False]]]])`¶
> …
> If *dir* is specified, the file will be created in that directory; otherwise, a default directory is used. The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the *TMPDIR*, *TEMP* or *TMP* environment variables. There is thus no guarantee that the generated filename will have any nice properties, such as not requiring quoting when passed to external commands via `os.popen()`.

I would expect this to work wherever I am, and in fact, Condor sets one of those environment variables to override the default temporary directory. It just ends up being the execution directory of the Condor job/worker. Could the worker do the same for the task to provide full encapsulation?

**Comment by btovar** [comment]
I'm going to create a tmp directory inside each task directory, and set TMPDIR to that.

A correct chmod to CONDOR_SCRATCH seems more trouble than its worth.

**Comment by btovar** [comment]
@matz-e: I wonder if you really want to save that output. Are you using it at all? In some cases it increases your disk usage way above what you ask for disk in condor.

**Comment by matz-e** [comment]
No we don't really want to do that…
