### ISSUE TITLE
Error in the HowTo example of the cctools API documentation

### ISSUE THREAD

**Issue by Nekel-Seyew** [cooperative-computing-lab/cctools#1408]
There are two errors: 

1)Makefile requires "Makefile.config" but only etc/config.mk exists, need to change Makefile to reflect this update.

2) stringtools has undefined reference to "log", "floor", "fmax", "fmin", "pow", fix: add "-lm" to CCTOOLS_BASE_LDFLAGS in config.mk

**Comment by Nekel-Seyew** [comment]
Fixed the first issue. The second issue is an issue in the configuration script?

**Comment by dthain** [comment]
Aha, I think the how-to is a little out of date with respect to the rest of the code.
Yes, config.mk should be used instead of Makefile.config.
And I think the example should put `$(CCTOOLS_EXTERNAL_LINKAGE)` in the linker line, since that has all of the various dependent libraries.

Please go ahead and fix it and make a pull request.

**Comment by dthain** [comment]
@Nekel-Seyew you can fix this one.

**Comment by btovar** [comment]
@Nekel-Seyew: is this still an issue?

**Comment by Nekel-Seyew** [comment]
I think this can be closed. I have no idea where in the documentation it's referring to any more. The reference about stringtools needing -lm is still valid, if you're compiling with it by hand. It really only seems necessary for the "string_metric" function, which also uses log, pow, fmin, fmax". One possibility would be to have local copies of those functions, since it does seem a little odd for a module called "stringtools" to need the math library. Then again, it's not really a big deal.

**Comment by Nekel-Seyew** [comment]
@btovar this can be closed.
