### ISSUE TITLE
work_queue_factory -T sge not submitting

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1485]
Using work_queue_factory on sge is not currently actually submitting.

2016/09/21 12:35:49: |submitted: 0 |needed: 5 |waiting connection: 0 |requested: 5
No change this cycle.

Unable to read script file because of error: error opening file: No such file or directory
2016/09/21 12:35:49.51 work_queue_factory[38873] notice: job submission failed: no output from sge

**Comment by dthain** [comment]
The problem here is that the factory does a `chdir()` into a scratch directory in `/tmp` before submitting jobs.

But sge (and related batch systems) expect that the application will read (and write) status files in the shared filesystem in the CWD where work_queue_factory was started.

A temporary workaround is to give the argument `-S .` but we need a better solution.

@btovar is the Lobster group using the factory in any mode except `-T condor` ?

**Comment by btovar** [comment]
They are not.

**Comment by dthain** [comment]
PR #1494
