### ISSUE TITLE
How to have a hierarchical(embeded) makeflow pipeline? 

### ISSUE THREAD

**Issue by zyli5313** [cooperative-computing-lab/cctools#1687]
Hi,

Just wondering how to have a hierarchical(embeded) makeflow script? Say for example, I have a fileA.mf file that has 
"targetA: dependesB
python foo.py"

And in foo.py I want to also have a sub pinpline that is not in fileA.mf. i.e. I want to embed a another makeflow pipeline in foo.py and do a blocking run after I have finished running foo.py. Is there way to do it?

I have tried to put everything in one fileA.mf now by adding additional targets and dependencies, which is cumbersome. 

Thanks!

**Comment by btovar** [comment]
Jake,

There is experimental code, where you can specify recursive calls as follows:

targetA: dependsB
         MAKEFLOW  myothermakeflow

You would have to decompose foo.py, so that the makeflow needed is myothermakeflow, and call the rest of foo.py in a rule as needed.

Let me know if that works for you. As I said, it is a little experimental, so there might be issues we are not aware of.

Ben

**Comment by zyli5313** [comment]
Hi Ben,

Understood. I tested it and it worked for me with very simple examples. Will let you know if I have find some issues.

Thanks,
Jake

**Comment by btovar** [comment]
Excellent, thanks for letting us know.
