### ISSUE TITLE
why  it just show "parsing a.mf" when I execute the software makeflow ?

### ISSUE THREAD

**Issue by WinterLi1993** [cooperative-computing-lab/cctools#1702]
HI,
   when run makeflow ,I met a problem ,as the following link : 
   [ThisShow](http://chuantu.biz/t5/149/1500972393x3027098406.png)
  the terminal always show 'parsing a.mf' 
  $ makeflow a.mf 
   parsing a.mf...

 what happened ?

**Comment by WinterLi1993** [comment]
HI,is any method to check makeflow file grammar ?

**Comment by WinterLi1993** [comment]
my command as the below : 
out :  input 
      perl  fpfilter.pl --min-var-freq 0.01 --vcf-file a.vcf --bam-file b.am --sample tumor  -r ref.fa -o a.filter.vcf && grep -e "#"  -e PASS > tmp.vcf && echo 'done' > done.log 

I doublt that maybe that's the problem of '--min-var-freq' .

**Comment by btovar** [comment]
How big is your makeflow file? How many rules?

You can try:  makeflow_analyze --syntax-check  a.mf

**Comment by btovar** [comment]
I can reproduce the hang, let me see what's going on.

**Comment by btovar** [comment]
Note that:
grep -e "#" -e PASS > tmp.vcf     does not have an input file.  Are the first && supposed to be ||?

Also -e "#" -e PASS means lines that both contain # and PASS. Is that what you mean?

Lines such as 'echo done > done.log' usually don't work very well. The problem is that each rule overwrites the done.log file. This is true even if you use '>>', as rules may execute in parallel. Thus,
I would rewrite your rules like this:

```
a.filter.vcf : fpfilter.pl a.vcf b.am ref.fa
    perl fpfilter.pl --min-var-freq 0.01 --vcf-file a.vcf --bam-file b.am --sample tumor -r ref.fa -o a.filter.vcf

LOCAL a.tmp.vcf : a.filter.vcf
    grep -e "^\#.*PASS" > a.tmp.vcf
```

The bug of makeflow made apparent by your original rule is that the # is being interpreted as a comment by makeflow. If I use:

perl fpfilter.pl --min-var-freq 0.01 --vcf-file a.vcf --bam-file b.am --sample tumor -r ref.fa -o a.filter.vcf && sh -c 'grep -e "\#" -e PASS > tmp.vcf && echo done > done.log'

then it works.

**Comment by zeronot** [comment]
@btovar ,
         the cmd "perl fpfilter.pl --min-var-freq 0.01 --vcf-file a.vcf --bam-file b.am --sample tumor -r ref.fa -o a.filter.vcf &&  grep -e "\#" -e PASS a.filter.vcf  > tmp.vcf  &&  echo done > done.log " is work.
       "Lines such as 'echo done > done.log' usually don't work very well. The problem is that each rule overwrites the done.log file."  ，different rule will genereate different name log file, so  that won't overwrites the done.log file . and "" && echo done > diffName.log" is oK for makeflow ?

**Comment by btovar** [comment]
Indeed, if every output file has a different name, then it should be ok.
