### ISSUE TITLE
Resource Monitor Snapshots

### ISSUE THREAD

**Issue by klannon** [cooperative-computing-lab/cctools#1714]
It would be very helpful if the resource monitor could take snapshots whenever either (a) a particular file appeared or (b) a line matching some kind of regexp appeared in a given file.  The basic idea is that if you could do that, then the resource monitor could watch your output directories and use the log files to decide when to take snapshots.  That way, you could not only detect when programs are starting, but also when they have changed from one phase to another (e.g. looking for the phrase, "Initialization complete" in a log file and snapshotting then).

If I were implementing this, I would pass the resource monitor a text file in which each line represents a file that the resource monitor should look for and optionally a regex inside the file to watch for.  The resource monitor would start on line one and watch for the file specified there to appear.  If a regexp is also specified, it would wait until it sees a line in the specified file that matches the regexp.  Once a match to a line has been seen, it would move to the next line.

With this example implementation, if I wanted to tell the resource monitor to take a snapshot when it sees `setup.log`, `prepare.log`,`running.log`, a line with `Initialization complete; Start processing` in `running.log`, and `transferoutput.log`, the text file passed to resource monitor would look something like the following:

```
setup.log
prepare.log
running.log
running.log "Initialization complete; Start processing"
transferoutput.log
```

Of course, I don't care how its implemented, as long as the basic functionality is available.  Let me know if you have questions.

**Comment by btovar** [comment]
In #1757,  for task t, you would say:

t.specify_snapshot_file("file")

where "file" would looks:
```json
{
    "setup.log":{
        "events":[
            {
                "label":"setup_started",
                "on-create":true,
                "count":1
            }
        ]
    },
    "prepare.log":{
        "events":[
            {
                "label":"prepare_started",
                "on-create":true,
                "count":1
            }
        ]
    },
    "running.log":{
        "events":[
            {
                "label":"setup_started",
                "on-create":true,
                "count":1
            },
            {
                "label":"processing_started",
                "pattern":"Initialization complete; Start processing",
                "count":1
            }
        ]
    },
    "transferoutput.log":{
        "events":[
            "label":"txoutput_started",
            "on-create":true,
            "count":1
        ]
    }
} 
```

The "count" 1 is simply there for efficiency, to stop checking after the first time an event is detected. The default is -1, which means  no limit in the number of times an event may happen.

Note that this changes specify_snapshot_file from the queue to task, and that the file is a json-document you provide, rather than a file the task produces.

In the summary file, the snapshots appear under "snapshots", in the order they happen, and with a the key "snapshot_name", a comma separated list of label(count),label(count),..., that indicates the events that happened, and how many since last check. (For example, if an event has an on-create, and a pattern, the count may be two, or if the pattern matches more than one line since last check, etc.).
