### ISSUE TITLE
Work Queue Worker Resource usage

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1726]
Currently, a Worker will only use a 1 core by default. As this is a consistent point of confusion with the user, the default behavior should be to use all of the available resources unless specified differently.

**Comment by btovar** [comment]
You mean the work_queue_worker executable?

**Comment by nhazekam** [comment]
Yes.

**Comment by nhazekam** [comment]
Am I under the wrong assumption of not labeling the worker?

**Comment by dthain** [comment]
Technically, this is just a matter of changing `manual_cores_option` in `work_queue_worker.c` to a value of zero (meaning automatic) instead of one (meaning one).

Although I was initially very cautious about making the worker use multiple cores by default, I more inclined to move this direction now, since multiple tasks per worker is a selling point of WQ, and users tend to miss out on it...
