### ISSUE TITLE
parrot does not compile on stampede 2

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1727]

**Comment by nhazekam** [comment]
The first issue that we run into on Stampede2 is:

`COMPILE chirp_wrap.o`
`gcc: error: strict: No such file or directory`
`gcc: error: unrecognized command line option ‘-fp-model’`

This reproduces the error originally from CJ.

The option `-fp-model` is pulled from the installed python's `sysconfig.get_config_var('CFLAGS')` in our configure script.
This is an icc option not recognized in gcc. If the option is removed from our config.mk we are able to compile with python bindings.

**Comment by nhazekam** [comment]
The second issue that we run into is broken `parrot_run` build:

`COMPILE parrot_run`
`/opt/apps/gcc/5.4.0/bin/ld: /opt/apps/gcc/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/libgcc_eh.a(unwind-dw2-fde-dip.o)(.text+0x184a): unresolvable R_X86_64_NONE relocation against symbol '__pthread_key_create@@GLIBC_2.2.5'`
`/opt/apps/gcc/5.4.0/bin/ld: final link failed: Nonrepresentable section on output`
`collect2: error: ld returned 1 exit status`

I am still working out what the cause of this is. Possibly due to the fact that we are trying to use a static glibc and the glibc may change with the module load.

**Comment by dthain** [comment]
I believe we decided to address this by using `vc3-builder` to deliver the appropriate dependencies.
Is that correct?

**Comment by dthain** [comment]
@nhazekam did this get fixed or is it still outstanding?

**Comment by nhazekam** [comment]
I think this may still be outstanding. I will devote some time early next week to investigate. I may have to renew my allocation for this resource.

**Comment by dthain** [comment]
@btovar I believe you made some progress on this?

**Comment by btovar** [comment]
Indeed. Fixed with #1957
