### ISSUE TITLE
Large UDP Updates Sometimes Lost

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1732]

**Comment by dthain** [comment]
It's not yet clear from observations whether makeflow is *sending* port zero or something is lost in transmission and the catalog *receives* port zero.  (Does port zero even have a useful meaning?)

**Comment by btovar** [comment]
I think it is a red-herring.

Specifying  a project name with -M, but not using -Twq, causes makeflow to report to the catalog using port 0.

During virtualclusters testing, I indeed forgot -Twq more than twice.

**Comment by btovar** [comment]
Nevermind. port 0 also appears with -Twq.

**Comment by dthain** [comment]
Keep in mind that with `-Twq`, makeflow will send two updates: a makeflow-level report, which will have port 0, and also a workqueue level report, which will have port not zero.  Does that explain the behavior?

**Comment by dthain** [comment]
@nhazekam is looking at this too

**Comment by btovar** [comment]
I think it does, yes.

**Comment by dthain** [comment]
Ok, so let me summarize my understanding so far:

- Receiving a message with port=0 at the makeflow level is not a problem per se.  That's just the high-level status message available via makeflow_status.
- When `-T wq` is given, the catalog should *also* receive a message from the work queue layer, with a valid port number in the JX document.
- The port number in the JX document may not necessarily match the source port number given by `datagram_recv` due to network translation issues.    This is expected.
- So, the problem that Nick is observing is really that when he runs makeflow with `-T wq` from Jetstream, it seems that the makeflow layer packet arrives, but the WQ layer packet does not.

@nhazekam is that correct so far?

@btovar are you observing a bug not explained by the above?

**Comment by nhazekam** [comment]
This is correct.

As mentioned above the port is not determined by where the message is located, but by what the message indicates the port is in the JX. The Makeflow message does not provide a port, so the port is 0 by default.

After running a small test last night (and after a suggestion from @nkremerh and @trshaffer), we found that if we replace the larger work queue message with a small test message, aka `test`, the packet goes through. Is it possible that the UDP packet is just being dropped in transit due to its size? The makeflow message is well under 1024 bytes and the wq message if almost 2048.

**Comment by dthain** [comment]
That's certainly possible.  Try using the `catalog_update` tool to send JX of larger sizes, and see if that gets dropped as well.  If that's the case, then we should look into paring down the WQ message.

(For a variety of reasons, it's also probably time that we allow for TCP updates to the catalog)

**Comment by nhazekam** [comment]
Will do. I'll test from both Jetstream machines to see if there is anything variable about which machine you land on and luck of the draw.

I am not sure if this totally explains the issue unfortunately because Work Queue applications send updates consistently, whereas the makeflow->wq combo does not.

**Comment by nhazekam** [comment]
Using a basic WQ message from the catalog, the length was 1400. I cut it down to several different sizes.

Messages of size 256, 512, 1024, 1028, 1280, 1300 do update.
Messages of size 1320, 1350, 1400 do NOT update.

This was consistent between both of my Jetstream machines.

**Comment by dthain** [comment]
Ok, so please post the JX text of the full update here, and let's discuss if anything can be pruned.

**Comment by nhazekam** [comment]
{
"name":"js-169-57.jetstream-cloud.org",
"lastheardfrom":1505405709,
"address":"149.165.169.57",
"tasks_total_disk":0, "tasks_total_memory":0, "tasks_total_cores":0,
"categories":[{"max_allocation_count":1,"first_allocation_count":0,"workers_able":0,"tasks_cancelled":0,"tasks_failed":0,"tasks_done":0,"tasks_dispatched":0,"tasks_running":0,"tasks_waiting":1,"category":"default"}],
"network_interfaces":[{"family":"AF_INET","host":"172.29.52.4","interface":"ens3"},{"family":"AF_INET","host":"172.17.0.1","interface":"docker0"}],
"version":"6.1.5 FINAL",
"owner":"nhazekam",
"working_dir":"/home/nhazekam",
"starttime":1505405649,
"project":"jet-test-special",
"type":"wq_master",
"gpus_largest":0,"gpus_smallest":0,"gpus_total":0,"gpus_inuse":0,
"disk_largest":0,"disk_smallest":0,"disk_total":0,"disk_inuse":0,
"memory_largest":0,"memory_smallest":0,"memory_total":0,"memory_inuse":0,
"cores_largest":0,"cores_smallest":0,"cores_total":0,"cores_inuse":0,
"workers_largest":0,"workers_smallest":0,"workers_total":0,"workers_inuse":0,
"master_preferred_connection":"by_ip",
"capacity_disk":10240,"capacity_memory":5120,"capacity_cores":10,"capacity_tasks":10,
"bytes_received":0,"bytes_sent":0,
"time_workers_execute_exhaustion":0,"time_workers_execute_good":0,"time_workers_execute":0,
"time_application":690,"time_polling":51611690,"time_internal":4112974,
"time_status_msgs":849683,
"time_receive_good":0,"time_send_good":0,
"time_receive":672644,"time_send":1253036,
"time_when_started":1505405649791241,
"tasks_complete":0,"tasks_exhausted_attempts":0,"tasks_cancelled":0,"tasks_failed":0,"tasks_done":0,"tasks_dispatched":0,"tasks_submitted":1,"tasks_with_results":0,"tasks_running":0,"tasks_on_workers":0,"tasks_waiting":1,
"workers_lost":0,"workers_blacklisted":0,"workers_fast_aborted":0,"workers_idled_out":0,"workers_released":0,"workers_removed":0,"workers_joined":0,"workers_able":0,"workers_busy":0,"workers_idle":0,"workers_init":0,"workers_connected":0,"workers":0,
"tasks_left":0,
"priority":0,
"port":9123
}

**Comment by dthain** [comment]
Ok, here is the plan:

@btovar please go through the worker update code and eliminate any unneeded fields.
@nhazekam please update the catalog client update code and compress the datagram with zlib before sending.  Prefix it with a letter `Z` so that the catalog knows what it is.
@dthain will add a bit to the catalog code to decompress datagrams as needed.

Long term, we need to add support for TCP updates.

**Comment by dthain** [comment]
Slight change: the first character of the update should be 0x1A (Control-Z) to indicate a compressed packet.

**Comment by btovar** [comment]
One issue to consider is that we use the result of queue_to_jx as the catalog update. Most stats of the queue, such as the category information are accessed only by work_queue_status -A, but work_queue_status contacts the master directly for that.

I propose to add another function, queue_update_to_jx, with information to find the master, and the information that the factory and work_queue_status (without arguments) needs. 

In that way, most of the time_.* and  workers_.* and tasks.*, and categories can be dropped form the update.

**Comment by dthain** [comment]
That sounds like a good approach.

**Comment by dthain** [comment]
Ok, so we decided to solve the problem on all fronts at once:
1 - Send less data to the catalog.  PR #1736 
2 - Compress updates sent and received.  PR #1734 #1735 
3 - Modify the catalog to accept TCP updates in a pinch.  PR #1739  (not merged yet)

Do we need any additional steps to get this deployed?

**Comment by nhazekam** [comment]
PR #1735 should not be merged until the catalog is running the most up-to-date version so that anyone that uses bleeding edge master won't send compressed information to an older catalog. @btovar also suggested that maybe compression is off by default and you use the environment variable to enable it instead.

**Comment by dthain** [comment]
Ok, why don't you change #1735 to be uncompressed-by-default, then you can merge safely.
Do we need to then deploy a new catalog immediately, or is the "lean update" sufficient to solve the problem for the moment?
If so, then I can spend a little time getting the tcp updates merged as well.

**Comment by nhazekam** [comment]
Will update #1735. Lean updates should be sufficient, but I will let you know if the problem persists.

**Comment by dthain** [comment]
I updated the master catalog server, please give it a try with compressed updates.

**Comment by dthain** [comment]
The backup server is also running with compression support now.

**Comment by nhazekam** [comment]
It hit both and they recognized the master.

**Comment by dthain** [comment]
Whew

**Comment by btovar** [comment]
Closing, as TCP updates has its own ticket.
