### ISSUE TITLE
Catalog Update Changes Leaves Out Master Time Stats

### ISSUE THREAD

**Issue by nkremerh** [cooperative-computing-lab/cctools#1744]
The message compression we have been working on for WQ talking to the catalog server has led to the catalog not receiving stats on how the master is spending its time. This in turn makes a portion of our WQ status visualization not all that useful. Stats used by the visualization (which reads from the catalog server) are:

time_send
total_send_time
time_receive
total_receive_time
time_polling
time_internal
time_status_msgs
time_application

**Comment by nkremerh** [comment]
@btovar @nhazekam Thoughts?

**Comment by dthain** [comment]
Ok, so we had to break this in order to fix the immediate problem of *all* data being lost.
Now that we have had some time to think about it, I propose the following general fix:

First, `catalog_send_update` should look at the size of message to be sent:
- If greater than some threshhold (say, 1200 bytes) then send it uncompressed and return success.
- If the compressed data is now less than the threshhold, then send it and return success.
- Otherwise, return failure.

Second, `update_catalog` in work queue should try the following: create a full update message and try to send it.  if that fails, then generate the "lean" update message and send that.

With those two things in place, then we have a solution that degrades gracefully: uncompressed data is preferred, then compressed, then reduced data.

(The threshhold should be adjustable by an environment variable.)

@nhazekam @nkremerh @btovar does that make sense to you?

**Comment by btovar** [comment]
Makes sense to me.

**Comment by nkremerh** [comment]
I agree.

**Comment by nhazekam** [comment]
Sounds good to me.
