### ISSUE TITLE
glibc problem between rh6 and rh7

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1768]
This came up before, just making a note for it.

Currently, some of my workers fail with:

condor_exec.exe: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by condor_exec.exe)

condor_exec.exe is a work_queue_worker compiled for RH7, but running on RH6.

**Comment by dthain** [comment]
Are you suggesting that we attempt to solve this within cctools?
Or do better OS matching within Condor?

**Comment by btovar** [comment]
I'm getting this with the wq_factory and condor_submit_workers.

In ND, we could improve the matching on the class ad glibc_version, but this won't solve it in the general. I would say to match on glibc_version, and add to the documentation how we solved it at ND.

**Comment by dthain** [comment]
Is the problem that `work_queue_factory` is submitting workers, but the requirements are not specific enough to match a suitably compatible machine?

**Comment by btovar** [comment]
It seems that way. The constraints are the automatic TARGET.Arch, and TARGET.OpSys.  The later is simply "LINUX".

**Comment by dthain** [comment]
I think this is a general problem between HTCondor and Linux, and the solution is usually in the HTCondor installation, to make sure that SUBMIT_EXPRS are set so that the execute machine matches the submit machine.

I think this comes up particularly here b/c we have deliberately set up condor to match to heterogeneous machines...

**Comment by btovar** [comment]
Closing, as more related to condor installation than work queue.
