### ISSUE TITLE
Resubmit task after failure

### ISSUE THREAD

**Issue by isanwong** [cooperative-computing-lab/cctools#1800]
Can makeflow add a parameter like --retry = 5, to try to resubmit task to batch/work queue? In the real world using env, we encounter task failures because of insufficient reource and other reasons. But if the failed task is the high-level node in the dag tree, then if we re-submit the whole makeflow after the whole makeflow failed, the total running time will be delayed.

**Comment by dthain** [comment]
I think the option you are looking for is already there:
https://ccl.cse.nd.edu/software/manuals/man/makeflow.html

Let us know if it works for you.

**Comment by isanwong** [comment]
Sorry, I didn't see that before ... 
Will the makeflow try to resubmit the failed job to other agents excluding the failed one? And does there exist a time window among retry actions?

**Comment by isanwong** [comment]
After a test, I found that the param --retry does not resolve my problem. What I need is that if a task failed, the makflow will wait for a specific time range (such as 20mins) and then try to rerun the task.

**Comment by dthain** [comment]
(Happy Thanksgiving, just catching up after the holiday break.)

Hmm, let me try to understand your problem a little better.

Two questions:
1 - What batch system are you using with Makeflow?
2 - What sort of problem are you experiencing that requires a wait of 20 minutes?

I ask b/c it is usually the batch system's drop to retry failures such as network outages, machine incompatibility, and that sort of thing.  That's a better place to retry the failure, since the batch system knows the context and the reason behind the failure.  Makeflow can always return the job to the batch system, but it doesn't necessarily have access to any information about why and where it failed.

**Comment by isanwong** [comment]
Hi, let me answer your questions first:
1. We use Work Queue as our batch system (because Makeflow does not support resource constraints on Torque);
2. What we are experiencing, is not the submission failure, is the runtime failure, for example, after a 20 minutes running, the job was killed by the system because of the memory overflow;

The problem is, we can rerun the makeflow after the whole makeflow failed, but there is time waste.

Thank you very much.

**Comment by dthain** [comment]
Hmm, it sounds like this problem is more complicated than it first appears, and I'm not sure that adding a simple retry is going to fix it.  Would you be willing to set up a brief telecon with a member of our team, so that we can understand the problem and propose a suitable solution?

**Comment by dthain** [comment]
Closing b/c no response after six months.
