### ISSUE TITLE
Another parrot bug with process substitution and redirection

### ISSUE THREAD

**Issue by khurtado** [cooperative-computing-lab/cctools#1855]
Hi, when I try to run script in [1] in a wrapper [2], with parrot and nohup + redirecting the stdout/err as in:

```
nohup ./parrot_cvmfs_static_run ./bug_wrapper.sh>nohub1 2>&1 &
```
I get the dump of some SQLite 3 stuff rather than the "Hello" at the end of the script:

```
nohup: ignoring input
LibCvmfs version 2.4, revision 25
SQLite format 3
ø^Qßâ<95>­MÇ»^Y^HÛ^M<91>^Q<8d>^B
...
```
Some notes:
1. Not using nohub+redirection actually makes the script work. 
2. Running `bug.sh` without the wrapper, even with nohub+redirection also seems to work.
I tried to isolate the issue as much as possible. This should be reproducible without any CMS credential.

[1]
```
#!/bin/bash

for FS in \
   oasis.opensciencegrid.org \
   singularity.opensciencegrid.org \
; do
    if [ -e /cvmfs/$FS/. ]; then
        REV_VAL=`/usr/bin/attr -q -g revision /cvmfs/$FS/. 2>/dev/null`
    fi
done

TS_VAL=`(cat /cvmfs/oasis.opensciencegrid.org/osg/update.details  | egrep '^Update unix time:' | sed 's/.*: //') 2>/dev/null`

source "/cvmfs/cms.cern.ch/cmsset_default.sh"

tmpname=`mktemp --tmpdir=$PWD installed_cms_software.XXXXXX`
SCRAM_ARCH="slc6_amd64_gcc481"
scramv1 list -c CMSSW | grep CMSSW | awk '{print $2}' | sort | uniq | grep ^CMSSW >> $tmpname
rm $tmpname

# Do process substitution
while read line
do
    echo $line
done < <(echo "Hello")
```
[2]
```
#! /bin/bash

./bug.sh
```

**Comment by trshaffer** [comment]
This was a tricky bug to track down, as it is only likely to show up when using bash process substitution and CVMFS. Big thanks to @khurtado for finding a case that reliably reproduces the issue!

When using process substitution, bash sends the output of a process through a pipe, and replaces it on the command like with a path like `/dev/fd/63`, where `/dev/fd` is a symlink to `/proc/self/fd`. Parrot needs to rewrite accesses to `/proc/self` as they would go to Parrot itself rather than to the child process. Parrot explicitly checks for symlinks starting with `/proc/self` and rewrites them to start with `/proc/$CHILD_PID`. For a symlink with `/proc/self` in an intermediate directory component, as is the case with `/dev/fd`, Parrot doesn't notice that it's touching `/proc/self` and simply calls `readlink()`. The kernel then resolves the intermediate symlink as pointing to Parrot. Here's a minimal example showing this behavior.

    # we need parrot to open a file descriptor we can easily identify,
    # so just use the debug log
    ./parrot_run -dall -o /tmp/parrot.log bash

    # this symlink is handled correctly
    $ ls -l /dev/fd/
    total 0
    lrwx------ 1 tshaffe1 dip 64 Feb 14 12:14 0 -> /dev/pts/3
    lrwx------ 1 tshaffe1 dip 64 Feb 14 12:14 1 -> /dev/pts/3
    lrwx------ 1 tshaffe1 dip 64 Feb 14 12:14 2 -> /dev/pts/3

    # the log is the first thing parrot opens, so it will be at fd 3
    $ head /dev/fd/3
    2018/02/14 12:14:34.69 parrot_run[29703] debug: ./parrot_run version 7.0.0  (released 2018-02-14 11:41:11 -0500)
    2018/02/14 12:14:34.69 parrot_run[29703] debug: Built by tshaffe1@cclws19 on 2018-02-14 11:41:11 -0500
    2018/02/14 12:14:34.69 parrot_run[29703] debug: System: Linux cclws19 3.10.0-514.6.2.el7.x86_64 #1 SMP Fri Feb 17 19:21:31 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
    2018/02/14 12:14:34.69 parrot_run[29703] debug: Configuration: --strict
    2018/02/14 12:14:34.69 parrot_run[29703] process: I am process 29703 in group 29703 in session 27717
    2018/02/14 12:14:34.69 parrot_run[29703] debug: command:
    2018/02/14 12:14:34.69 parrot_run[29703] debug:  - ./parrot_run "-dall" "-o" "/tmp/parrot.log" "bash"
    2018/02/14 12:14:34.69 parrot_run[29703] debug: environment:
    2018/02/14 12:14:34.69 parrot_run[29703] debug:  - HOSTNAME=cclws19
    2018/02/14 12:14:34.69 parrot_run[29703] debug:  - TERM=xterm-256color

In this example, a child can only see its own file descriptors in `/proc`, but can access Parrot's file descriptors by blindly opening them. Coming back around to the original bug, Parrot doesn't normally open 60 file descriptors at once, so this eager symlink following stops with `ENOENT`. Parrot's next step is a hard-coded check for `/proc/self` and `/dev/fd`, so it rewrites the paths and everything works OK. It turns out that libcvmfs (linked into Parrot, and thus in the same process) opens a large number of file descriptors for IPC channels, catalog files, etc. The process substitution in `bug.sh` reads from `/dev/fd/63`, which happens to point to one of the SQLite catalog files libcvmfs has open, hence the garbage output. I guess the open file descriptors only line up under the conditions of the bug (running under `nohup`, wrapper script).

I'm currently looking at how to fix Parrot's symlink handling.
cc @dthain

**Comment by dthain** [comment]
If I understood your explanation, Parrot is attempting to address /dev/fd by just following the symlinks naturally.  And we can't catch all of the intermediate-symlink cases.

Could we make this a more targeted solution by simply hard coding a name-mapping from `/dev/fd` to `/proc/[pid]/fd` just like we hard code `/proc/self` -> `/proc/[pid]` ?

**Comment by trshaffer** [comment]
We already do that, but it happens *after* following the symlink, so Parrot forgets the original path. I don't think we can get around this unless Parrot resolves intermediate symlinks itself.

**Comment by dthain** [comment]
Come on over and let's talk about it.

**Comment by trshaffer** [comment]
@khurtado I can get your example to run correctly on #1860

**Comment by khurtado** [comment]
@trshaffer It does work indeed! Thanks!
