### ISSUE TITLE
Does Makeflow respect MEMORY, CORES, etc.?

### ISSUE THREAD

**Issue by kwwette** [cooperative-computing-lab/cctools#1953]
According to

https://ccl.cse.nd.edu/software/manuals/makeflow.html#resources

one can tell Makeflow what e.g. memory is required by setting a directive in the `.makeflow` file:

```
$ cat tmp.makeflow
MEMORY=428

out:
    /bin/sleep 60; touch out
```

However this feature doesn't seem to work if the job is run under Slurm:

```
$ makeflow -T slurm tmp.makeflow
parsing tmp.makeflow...
local resources: 36 cores, 191903 MB memory, 6776682 MB disk
max running remote jobs: 100
max running local jobs: 36
checking tmp.makeflow for consistency...
tmp.makeflow has 1 rules.
starting workflow....
submitting job: /bin/sleep 60; touch out
submitted job 960174
job 960174 completed
nothing left to do.
```

and I think query for what memory was requested

```
$ sacct -j 960174 -o JobID,ReqMem
       JobID     ReqMem 
------------ ---------- 
960174            100Mc 
960174.batch      100Mc 
960174.exte+      100Mc 
```
which shows the job was allocated the default 100Mb instead of the requested 428Mb.

What am I doing wrong here?

**Comment by btovar** [comment]
Karl,

Thank you for your report, let me check if something strange is going on.

**Comment by nhazekam** [comment]
Just to add to this. Currently the batch system behind Makeflow does not support specifying individual resources on a per task basis. This is largely due to the different way that resources can be specified and different requirements of which options need to be specified depending on the batch system and site. This was similarly discussed in #1857. 

If you are using the same resource requirement for all of the tasks, this can currently be accomplished using the `-B/--batch-options`. Any options specified here will be applied to each job submitted.

We are also discussing different ways that specifying resources on a per job basis for better support with Makeflow full set of features.

**Comment by kwwette** [comment]
@btovar Thanks very much!

@nhazekam Thanks. I'm new to Makeflow, so at the moment I'm just trying to get the basic example from the manual working, with just one task.

**Comment by nhazekam** [comment]
Apologies to @Nekel-Seyew, but I think for now lets see if standard Makeflow is able to address @kwwette's use case. Between Makeflow and Work Queue we should be able to accommodate most execution models and resources specification needs.

The MPI integration is still under development and very much a bleeding edge feature. If down the road we find that our current master version can not accommodate the use case this can definitely be revisited. Hopefully by then we as a team will have a better understanding of the code and its best use cases.

**Comment by dthain** [comment]
@nhazekam welcome back home, and please make it a priority to work on this one.  Touch base with @Nekel-Seyew for testing since he has been doing some work with SLURM on XSEDE.  @btovar let's get this and #1857 rolled up into a minor release when ready.

Now, there is always some uncertainty about whether adding command-line arguments to `qsub` or its equivalent will cause accidental breakage due to minor site differences.  I suggest we address this by adding a command-line option (maybe `--safe-submit-mode`) that will disable these extra arguments, in case anyone runs into trouble.

**Comment by dthain** [comment]
@nhazekam Any updates on this one?

**Comment by nhazekam** [comment]
@dthain @kwwette Sorry I didn't update this. This was somewhat recently addressed. SLURM now has support with respect to CORES and MEMORY. This is both in Master and in most recent release.

Using Makeflow each task is specified as 1 node and 1 task per node (-N 1 -n 1). The cores are specified using -c. Memory is specified using -mem. 

Disk is not specified for SLURM as a shared filesystem is typically assumed. The only similar option is -tmp which specifies the temporary disk space, but this options has varying support based on site and could have unexpected effect if used for disk.

Additional note: -mem is not supported on Stampede2 if that is you site of choice. The option --ignore-memory-spec leaves it off for Stampede2.

**Comment by nhazekam** [comment]
Resources are now specified (respect depends on batch system) in each batch specific job submission.
Torque support #1858 
SLURM #1858 
SGE #1981 

If there are cases where resources are incorrectly specified, please open a new issue with specific details.
