### ISSUE TITLE
Parrot CVMFS use Web Proxy Auto-Discovery

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#2015]
Check what the status and distance is needed from current Parrot configuration.

The goal is to allow for users of CVMFS via Parrot to use the WPAD to configure proxies automatically, which is supported for CVMFS and libcvmfs.

**Comment by nhazekam** [comment]
@jblomer @DrDaveD Just linking the issue so that you can follow this.

**Comment by trshaffer** [comment]
@DrDaveD I fiddled with the option passing for a while, and I think this should work as is. I only tested with a local PAC file, but CVMFS was correctly picking up proxy config. I set the `CVMFS_PAC_URLS` environment variable, and used the Parrot option `--cvmfs-option CVMFS_HTTP_PROXY=auto`. Under that configuration, libcvmfs successfully read in the config and set up proxies. Since libcvmfs does all the real work, I *think* everything should function as usual under Parrot.

**Comment by DrDaveD** [comment]
Thanks.  That's kind of an odd combination, requiring one to be an option and one an environment variable, but it's probably good enough, don't you think?

**Comment by trshaffer** [comment]
This should definitely be enough to get proxy autoconfig working. If you prefer to stick to environment variables only, Parrot recently started checking the `HTTP_PROXY` environment variable for this. `CVMFS_PAC_URLS` would appear to only work as an environment variable ([per libcvmfs](https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/wpad.cc#L163)). @jblomer might have an opinion on supporting that as a named option from libcvmfs.

**Comment by trshaffer** [comment]
Closing, as there are no changes necessary here
