### ISSUE TITLE
Makeflow Gets Stuck if Submit Always Fails

### ISSUE THREAD

**Issue by epyifany** [cooperative-computing-lab/cctools#2161]
Without specifying a remove job limit of 20(-J 20), makeflow -T amazon will be stuck in a loop of requesting for instances and amazon responding InstanceLimitExceeded.

This is a specific issue on amazon as other sources hold on to the jobs submitted.

It would be helpful to adjust part of makeflow_run in makeflow.c to wait after continuously failing to submit. 

YY

**Comment by dthain** [comment]
More generally, the problem here is that Makeflow expects any failure in batch_job_submit to be a temporary one: if submit fails, then makeflow just keeps retrying.

This assumption is not correct in the case of Amazon EC2, when the user has run out of available instances: batch_job_submit() will just fail over and over again.

What needs to happen is that, in the case of submit failure, the makeflow main loop should just continue so that it eventually calls batch_job_wait(), allows a job to exit, and then batch_job_submit() will be able to succeed.

**Comment by dthain** [comment]
Fixed.
