### ISSUE TITLE
jx_array_length function returns 1

### ISSUE THREAD

**Issue by camicarballo** [cooperative-computing-lab/cctools#2215]
It seems that jx_array_length always returns a value of 1 when called correctly on arrays of varying lengths.

**Comment by dthain** [comment]
Yikes!  Well, this is a good one for you to fix too.

(Perhaps it just hasn't been used elsewhere.  It would be a good idea to grep the sources just to see who/what is depending upon it.)

**Comment by btovar** [comment]
@camicarballo, I've just tested jx_array_length, and it does work as it should. Is it possible the error is somewhere else?

**Comment by camicarballo** [comment]
@btovar it seems that in TR_jx.sh when adding the line `"count" : len([1,2,3])` returns the length of an array where the single element is the array [1,2,3] for some reason.

**Comment by btovar** [comment]
I think the issue is in the `jx_function_len` function. It receives an array of arguments (say [ [1,2,3] ]) which is passed to jx_array_length. However it should only give the first element to  jx_array_length (that is [1, 2 ,3]).

In other words, jx_function_len should check that args has length 1, and pass that single first element of args to jx_array_length.

**Comment by camicarballo** [comment]
That is exactly the problem. Should I close this?
