### ISSUE TITLE
catalog updates tcp port always uses udp port + 1

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2267]
For example:

CATALOG_UPDATE_PROTOCOL=tcp   makeflow -C mycatalog:9097

Updates will be sent to mycatalog:9098, which is confusing. There is no way to specify the tcp port by itself.

**Comment by dthain** [comment]
This design was an imperfect compromise in order to get TCP updates quickly implemented without disrupting the code too much.  Here is how it works now:

A catalog is named by a single port P (usually 9097).  The catalog server then listens on:
- port P/tcp for HTTP queries.
- port P/udp for UDP updates.
- port (P+1)/tcp for TCP updates.

P+1 is clunky, but it has the nice property that we didn't have to add any information to the catalog name, which is expressed in environment variables, command line args, and so forth.  I see several possible ways to proceed here:

0 - Leave the code the same, but do a better job of documenting the behavior, for the sake of firewalls and such.

1 - Add options to the catalog to allow it to listen on an arbitrary port for TCP updates.  This would be easy to do, except that the client must be informed somehow.  We would have to have a syntax that accommodates multiple ports, and then document that for users.

2 - Consolidate the TCP updates into the existing HTTP query port.

2A - Have the catalog sniff the difference between a TCP update and an HTTP query.  This would only require the client to change the port number on which it sends updates.  The old port would have to stay around for compatibility reasons, for a while.

2B - Have the client send updates as a proper HTTP POST, and make the catalog do a little more parsing of verbs up front.  This would require  a little more work on the client side to send a proper POST.  The old port would still have to stay around for compatibility reasons, for a while.

Are there any other options I'm missing?

**Comment by btovar** [comment]
Closing as current design offers a simple compromise.
