### ISSUE TITLE
JX Project Behavior

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2313]
Likewise, either I'm misunderstanding the behavior of project or what it's expected to do:

Using jx_test:

```
{}
project( {"name":name, "port":port}, fetch("http://catalog.cse.nd.edu:9097/query.json"))
value:      error("on line 2, name: undefined symbol")
```

More simply:

```
{}
project( a, [ {"a":10}, {"a":20}, {"a": 30} ] )
value:      error("on line 2, a: undefined symbol")
```

I was expecting this to return:

```
[10,20,30]
```

What's the expected behavior here?

**Comment by nkremerh** [comment]
Interesting. I will have to look into this.

**Comment by nkremerh** [comment]
The simple example is failing because the context is empty when it is evaluated (https://github.com/cooperative-computing-lab/cctools/blob/master/dttools/src/jx_eval.c#L596). This top-level evaluation occurs _before_ project merges the context and each object being considered ({"a": 10}, ...).

If we bypass this by checking if context is empty in jx_eval (if so, skip lookup), we can essentially pass through to project's functionality of doing jx_merge(obj, context) which will then allow jx_eval to work as expected.

**Comment by dthain** [comment]
Hmm, I don't think that's it.  `jx_lookup` does the right thing if `context` is null or the wrong type: it just returns `NULL` indicating no such item:
https://github.com/cooperative-computing-lab/cctools/blob/master/dttools/src/jx.c#L173

I think this is another instance of lazy versus eager evaluation, right?  In `project(a,[x,y,z])` you don't want `a` evaluated until `project` begins to run and computes `eval(a,merge(x,context))`.  Alternatively, `eval(a,eval(x,context))`

**Comment by nkremerh** [comment]
We are saying the same thing.

**Comment by dthain** [comment]
Ok, propose a solution?

**Comment by nkremerh** [comment]
Either enforce lazy evaluation only for JX querying functions (select, project, fetch, schema) _or_ switch to all lazy evaluation for JX. The former I am willing to wrestle with, the latter is honestly far afield from my research goals and a guaranteed time sink.

Do you have an alternative?

**Comment by dthain** [comment]
I don't think it's necessary to do it for all JX functions.  In fact, I'm not sure that you should even make a blanket change to all the query-related functions.  Just determine the minimal change needed...

**Comment by nkremerh** [comment]
On it.

**Comment by nkremerh** [comment]
Fixed.
