### ISSUE TITLE
compilation error ("conflicting types for 'gettimeofday'")

### ISSUE THREAD

**Issue by bcdarwin** [cooperative-computing-lab/cctools#2327]
Compiling with various GCC versions from 4.9 to 7 and with glibc 2.31 on Linux (NixOS):

```
COMPILE parrot_namespace.o
LINK libparrot_helper.so
mkdir -p lib64
COMPILE lib64/libparrot_helper.so
parrot_helper.c:51:5: error: conflicting types for 'gettimeofday'
 int gettimeofday( struct timeval *tv, struct timezone *tz )
     ^~~~~~~~~~~~
In file included from parrot_helper.c:20:0:
/nix/store/lqn6r231ifgs2z66vvaav5zmrywlllzf-glibc-2.31-dev/include/sys/time.h:66:12: note: previous declaration of 'gettimeofday' was here
 extern int gettimeofday (struct timeval *__restrict __tv,
            ^~~~~~~~~~~~
make[2]: *** [../../rules.mk:29: libparrot_helper.so] Error 1
make[2]: *** Waiting for unfinished jobs....
parrot_helper.c:51:5: error: conflicting types for 'gettimeofday'
 int gettimeofday( struct timeval *tv, struct timezone *tz )
     ^~~~~~~~~~~~
In file included from parrot_helper.c:20:0:
/nix/store/lqn6r231ifgs2z66vvaav5zmrywlllzf-glibc-2.31-dev/include/sys/time.h:66:12: note: previous declaration of 'gettimeofday' was here
 extern int gettimeofday (struct timeval *__restrict __tv,
            ^~~~~~~~~~~~
make[2]: *** [Makefile:36: lib64/libparrot_helper.so] Error 1
ar rv libbatch_job.a batch_file.o batch_task.o batch_wrapper.o batch_job.o batch_job_amazon.o batch_job_amazon_batch.o batch_job_dryrun.o batch_job_chirp.o batch_job_cluster.o batch_job_blue_waters.o batch_job_condor.o batch_job_local.o batch_job_work_queue.o batch_job_lambda.o batch_job_mesos.o batch_job_k8s.o batch_job_mpi.o mesos_task.o
```

**Comment by dthain** [comment]
@bcdarwin thanks for the bug report.  It looks like trouble is occurring in places where we are overriding existing system calls.  Always tricky to do this in a maximally portable way.

@trshaffer please set up a suitable Nix environment and see if you can reproduce.

**Comment by bcdarwin** [comment]
To reproduce:

 - install Nix on a Linux system
 - clone the Nixpkgs repo (NixOS/nixpkgs or bcdarwin/nixpkgs) and checkout my (`bcdarwin`) `cctools` branch
 - run `nix-build -A cctools /home/ben/nixpkgs --show-trace -K` (this will print the location of the temporary build directory after it fails for further inspection)

**Comment by trshaffer** [comment]
@bcdarwin I can reproduce this issue (and #2326). Looks like there are quite a few places (especially in some of our less used code) that trigger warnings and block compilation. I'll let you know when I work through all of them.

**Comment by trshaffer** [comment]
This is caused by a hard error due to redefining a function with the wrong signature (not a warning, so no `-Wno-whatever` to suppress it). This function, and especially the second argument, seem to have been deprecated for a while. glibc recently (in 2.31) changed the way it's defined in `sys/time.h`. Summarizing the header from 2.30 and prior:

    #ifdef __USE_MISC
    typedef struct timezone *__restrict __timezone_ptr_t;
    #else
    typedef void *__restrict __timezone_ptr_t;
    #endif
    
    extern int gettimeofday (struct timeval *__restrict __tv,
                             __timezone_ptr_t __tz) __THROW __nonnull ((1));

2.31:

    extern int gettimeofday (struct timeval *__restrict __tv,
                             void *__restrict __tz) __THROW __nonnull ((1));

The `struct timezone *` form appears to be an older (possibly BSD or SysV derived?) feature, while Linux declares a `void *` expects `NULL`. Apparently glibc finally dropped support for the former mode. Unfortunately, this a problem for Parrot. Just from the distros we test with autobuild (and a bleeding edge one like Arch or the Nix environment referenced), I saw several different behaviors.
- `__USE_BSD` switches to the `struct timezone *` form. This is an internal macro, turned on via `_BSD_SOURCE`. `_BSD_SOURCE` and `_SVID_SOURCE` are deprecated aliases for `_DEFAULT_SOURCE`.
- `__USE_MISC` instead. This is turned on by either `_BSD_SOURCE` or `_SVID_SOURCE` (`_DEFAULT_SOURCE` on newer versions).
- No feature macros at all. Future glibc versions only allow the `void *` form.

To complicate things, defining `_GNU_SOURCE` and `-std=` (both of which we use) can imply features. Thus prior to 2.31 our default `CCFLAGS` resulted in the `struct timezone *` form. So there are a few options here:
- Compile `parrot_helper.c` with different flags. For this to work, we need a big warning in the Makefile not to touch these flags, or a helper script to figure out the appropriate flags at build time. We also need to test on our build platforms that the features don't get implied by another option (or turned on by default by some compiler). This would allow us to use only the `void *` form in the code. It would also constrain the rest of the `parrot_helper.c` to use only old features (probably not a problem as it's small). Also note that it's possible to create a mismatch here if `_GNU_SOURCE` changes the typedefs e.g. to support 64 bit file operations, so we would need to check that none of the other typedefs used in `parrot_helper.c` can vary based on feature flags. A mismatch between header typedefs would be terrible to debug, as we'd see either stack corruption or silent changes to function arguments.
- Don't include `sys/time.h`. `parrot_helper.c` just passes values on to Parrot, so it doesn't really need to understand them. Again, we need some big warnings to never touch the includes. We could just declare the time-related functions with `void *` and `int` arguments. This approach assumes that none of the other headers transitively include `sys/time.h` (may change in future versions of glibc?). Also note that like above some of the other functions use typedefs like `clockid_t` that could vary across platforms (probably unlikely?), so we would need to be careful here.
- Detect libc in `parrot_helper.c` (this PR). This appears to be a quirk of glibc, and while ugly this is the only way I could find to fix this that doesn't have the chance to introduce weird type mismatches. Works on all our platforms (including Mac), and with other libc's like musl (they just use `void *` unconditionally). It does have the advantage of being immediately obvious that something weird is going on, and fails loudly if something doesn't line up.

**Comment by dthain** [comment]
Appreciate the detailed writeup.  Of those, I think the last one is the minimally invasive, so you have the right solution here.  It would be helpful to add some of this explanation to the source so that future readers can understand more of the context.

Is this the only system call / library call with this sort of problem?

**Comment by trshaffer** [comment]
AFAIK yes, since `gettimeofday()` is a weird case. None of the other functions we replace are deprecated/in limbo like that. It might be a good idea to check over our other `LD_PRELOAD` libraries to look for warnings in the man pages though

**Comment by btovar** [comment]
Is parrot_helper.c actually used today? I don't remember any use case for years, thus the effort to fix it may not be worth the time investment.

**Comment by btovar** [comment]
The resource_monitor helper uses gettimeofday() indirectly via timestamp_get(). It includes "timestamp.h" with then includes "time.h".

**Comment by trshaffer** [comment]
It's not a problem unless you're *providing* `gettimeofday()` via `LD_PRELOAD` as `parrot_helper.c` does. If you're just calling `gettimeofday()` from within your code, the glibc change shouldn't be a problem (this is why they don't consider it a breaking change, as your other pointer arguments can just get implicitly converted to `void *`).

**Comment by trshaffer** [comment]
@bcdarwin you should be able to get things to compile under glibc 2.31 now
