### ISSUE TITLE
CCTools: Rename to Manager?

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2395]
@btovar please do a quick survey via grep to see the feasibility of renaming "master" to "manager" throughout.

To what extent would this involve:
a) Change to program names and options (likely to break current users)
b) Change to API details (possible to break current users)
c) Change to internal names etc (not likely to break anything)

**Comment by btovar** [comment]
a) 'master' is only used in documentation and command line arguments. Adding 'manager' and deprecating 'master' should not break current uses. 
b) When required, we use project name instead of master name, thus no break there. 'blacklist' is part of the wq API. We can change that to 'blocked_list' and deprecate 'blacklist.
c) Mostly messages to the catalog (wq_master, master_load, master_preferred_connection).

**Comment by dthain** [comment]
Ok, would you like to make a PR starting with just a few applications of sed, and see how that looks?

**Comment by btovar** [comment]
Sounds good!

**Comment by btovar** [comment]
sed probably won't cut it, as we need to preserve compatibility of options.

**Comment by dthain** [comment]
Would it work to start with sed to generate a draft PR, and then we go back
and fix things that shouldn't change?  I suspect the number of items is
quite small...
