### ISSUE TITLE
WQ: Handle false positives in fast abort

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2580]
The objective of Work Queue's fast abort mechanism is to detect workers that are executing tasks much more slower than the rest of the workers to disconnect and block them. This allows tasks running in the slow workers to be submitted somewhere else. For tasks with similar running times executing on heterogeneous or faulty workers this works well.

The way we detect slow workers is to keep track of the running times of tasks (either overall or per category), and check whether a task has been running on a worker longer than the average plus some user defined deviation.  This poses issues when a task that legitimately runs longer than its peers is found, as it always triggers the fast abort mechanism and it can never be completed.

Currently, other than logs, there is no information given to the Work Queue application that a task is being retried because of a fast abort.

Some possible solutions:

- No task can trigger the fast abort mechanism twice.
- If a task defines a limit end time, or wall time, then it cannot trigger fast abort.
- One task is not enough to trigger fast abort if other tasks have been executed at that worker in a reasonable amount of time.
- On any fast abort, stats of the worker are cleared to account for changing distributions.
- Tasks terminated because of fast abort are returned to the user to be resubmitted in a different category, with fast abort disabled, etc.

**Comment by dthain** [comment]
All these points have some value.  Let's look at it this way:

1 - What are the behaviors that we are trying to detect with fast abort?

2 - What are the behaviors that we **do not** want fast abort to detect?

That should help to clarify what changes to apply.

**Comment by btovar** [comment]
I think we should be careful conflating workers and tasks. We use tasks to trigger fast abort on workers, but classifying well behaved tasks is not the objective, instead tasks are the way we currently measure the health of  worker. Now, the issue is that simply using tasks' runtime to measure the health of a worker leads false positives. 

> 1 - What are the behaviors that we are trying to detect with fast abort?

Fast abort objective is to detect faulty workers, or workers that are executing tasks much slower than other workers. In particular, it is not about detecting task behavior. Ideal: We detect a task that has been running for a very long time in a worker compared to other tasks, we move it to another worker and it finishes in a time comparable to its peers.

> 2 - What are the behaviors that we do not want fast abort to detect?

We don't want well behaved workers to be terminated. Case to avoid: A legitimate long running task is move to other workers over and over again.

**Comment by klannon** [comment]
Of all these options, the first one (no task can trigger fast abort twice) is by far my favorite.  The second one is also a good idea.  In fact, in Lobster, we implement that manually by only setting the fast abort flag for tasks that don't define a runtime limit.  The last one is interesting because it changes the nature of fast abort, making it more visible to the user/application.  Right now, fast abort is entirely internal to Work Queue, at least as I understand it, so the user never finds out about a task that's triggering fast abort over and over because the task doesn't return until it reaches some maximum number of retries.

I think there are two scenarios we want to think about:
* The "inattentive user" scenario:  This could of course be a user who can't be bothered to check on his or her tasks regularly, but I also think there are legitimate cases where this is the right user behavior.  For example, if you've just submitted such a large pile of work that it's not supposed to finish for a week, it's natural that you won't want to check it every hour to see if there are problems.  When dealing with the inattentive user, I'd argue the right behavior is to "keep trying" so that when the user finally checks back, there's a chance the problem has been solved.  For fast abort, this means that you *do* want to fast abort (so that the user doesn't come back to find stuck jobs), but you don't want to give up retrying because the user doesn't want to come back to find that a task is fitting in the failed state but can be recovered just by a manual retry.
* The "vigilant user" scenario:  This is basically the opposite of the above.  The user is checking diligently the progress and thinks that she or he has spotted a problem.  This user wants a way to try to fix the problem.  If the problem is that a task has been "running" too long and this user wants to know how many times has it been fast aborted and what is the time limit being used.  This user will use that information to try to take some corrective action.

Instead of a hard limit on two fast aborts, what about increasing the fast abort time limit with the number of retries (e.g. double it every time there is a fast abort).  Thus, you'll keep trying, but you also will never be permanently stuck with an error that causes a task to hang.  This addresses the "inattentive user's" needs.

To address the "vigilant user" you'd want to have some way to get information on tasks that are being repeatedly fast aborted so that some action could be taken (e.g. disabling fast abort or increasing the multiplier to see if the task will finish with a longer running time).  I'm not really sure how to address this.  If you had the task back after a fast abort, you'll make the "vigilant user" happy but not the "inattentive user."  Does the API provide a way to get information on how many fast aborts each running task has triggered?  Can a task be recategorized?  I guess right now, there is definitely the solution of terminating and restarting WQ to reset all the statistics, but that's maybe a bigger hammer than we want to use to solve this problem.  Thoughts?

**Comment by klannon** [comment]
> Fast abort objective is to detect faulty workers, or workers that are executing tasks much slower than other workers.

I think this is only part of the story.  I think tasks can get "stuck" for transient reasons that have nothing to do with the worker on which they're running.  Imagine that you have some code that makes a remote DB connection.  Suppose the DB dies while the software is in the middle of the connection process in such a way that it is left waiting for a response that will never come.  Suppose also that this software has no timeout on that wait, so it will wait forever.  (We don't always get to choose what software we run, after all.  Some of it is just bad and we can't help it!)  This would be a case where fast abort is really valuable that has nothing to do with the nature of the worker.

**Comment by btovar** [comment]
Thanks Kevin, this is very helpful. What about:

1. A worker w is marked as "suspect" if a task t_a triggers the fast abort check.
2. t_a is terminated in worker w, a counter in t_a is increased to record the event, and t_a is submitted to another worker.
3. A suspect worker receives no more tasks.
4. A suspect worker with no running tasks is terminated.
5. For tasks still running on w:
5.a If any such task completes without triggering fast abort, then the worker is not considered suspect anymore.
5.b For any task t_b that triggers fast abort, go to point number (2).

Changes in the triggering mechanism:
- Use the counter per task to check whether the task is running past the time limits. The value of the counter is added to the multiplier given when activating fast abort.
- To reduce the number of parameters to specify, the number of times a task is retried is the number specified as the multiplier.
- A tasks that exhausts these retries is returned to the user with something like WORK_QUEUE_RESULT_FAST_ABORT.
