### ISSUE TITLE
WQ: Managing Remaining Time at Worker

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2590]
In some situations, workers are allocated at a site with a fixed amount of time.  When the clock is running down, we should not dispatch tasks to workers that have insufficient time remaining.

Feature is needed by LSST/DESC workflows running Parsl + WQ.

This will require several minor changes throughout:
- Figure out how to detect "time in allocation" at worker startup.
- Record expected shutdown time in worker, and convey back to manager.
- Tasks should be able to declare "time" as a resource to consume.
- Manager should not schedule tasks to workers with insufficient remaining time.

**Comment by dthain** [comment]
@benclifford can you add a little more background on the LSST/DESC use case?  What system are they attempting to use, and how does it publish the ending time of a job allocation.  (e.g. an environment variable given to the job?)

**Comment by benclifford** [comment]
The sites we're running on at the moment are all running slurm + workqueue driven by Parsl.

From a Parsl perspective, the provider mechanism that I talk about in https://github.com/Parsl/parsl/issues/2031 often knows the walltime that it is requesting for a job. In that case, it should be a straightforward plumbing exercise to (for example) wire that information through to some workqueue command-line option. I think that would overstate the amount of time available for workqueue workers by ~a minute due to startup times - I'm unsure if that is a problem.

I'm also (for now) not particularly concerned about making our users specify a separate (smaller) worker walltime manually in parsl configuration: they have dealt with far worse configuration horrors.

cc @tomglanzman who is more on the application side of this work.

**Comment by dthain** [comment]
Per @btovar, `work_queue_specify_time(task,time)` is already in there.  So we just need the pieces implemented from the worker side.

**Comment by TomGlanzman** [comment]
Ben has described the LSST/DESC needs.  Basically, given a sequence of "large" batch jobs each of N nodes and T hours, we are evaluating the use of workQueue within Parsl as a means of efficiently utilizing these computing resources (Cori at NERSC).  The jobs vary greatly in run time ranging from a few min to many hours.  We would like to avoid unnecessary CPU consumption where possible by only attempting to run Parsl tasks which have a chance of completing.

Getting the necessary data to make the time calculation will vary on batch system being used.  At NERSC, SLURM is used and one way to get this information is with the 'sacct' command, e.g.,

```
$ sacct -X --format=job%-15,submit,start,end,exitcode,nnodes,alloccpus,timelimit,elapsed,state
          JobID              Submit               Start                 End ExitCode   NNodes  AllocCPUS  Timelimit    Elapsed      State 
--------------- ------------------- ------------------- ------------------- -------- -------- ---------- ---------- ---------- ---------- 
41980221        2021-04-26T10:10:15 2021-04-26T10:10:21 2021-04-26T10:14:26      0:0        1        272   00:10:00   00:04:05 CANCELLED+ 
```
where Timelimit-Elapsed = wall clock time remaining.

**Comment by dthain** [comment]
#2593

**Comment by dthain** [comment]
#2593
