### ISSUE TITLE
Use JX expressions in the factory configuration file.

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2653]
E.g., if I want to define 4GB of memory per worker core, it would be great if we can simply say `cores*4000` or something like that.

**Comment by dthain** [comment]
@jmrundle here is a good place to start.  Please look at `work_queue_factory.c` (which is in the `batch_job`) module and start by evaluating the values in the configuration file as JX expressions.

**Comment by jmrundle** [comment]
@dthain Just want to make sure I'm understanding the idea correctly first...  So, ideally, the config file could include lines like this:
```
"cores":   8,
"memory":  cores * 4000,
```
In this case, it seems like the main approach is to parse the config into a JX object (which we do already), then try to evaluate each of the attributes as JX expressions, using the entire object as context to resolve symbols.

The only issue I can think of with this approach is that when a circular dependency is arranged, a segfault will occur.  For example, the following example parses correctly:
```
"cores": memory,
"memory": cores,
```
but later raises a segfault during `eval` when trying to determine the value associated with the key "cores".

Should the `eval` function fail quickly with an error message once a circular dependency is detected, or is the current segfault behavior good enough?

**Comment by dthain** [comment]
Yes, you have the right idea.  I think @btovar also had the idea that there could be some external parameter(s) that could be used in the values.

And I'm glad you are thinking about the circular evaluation problem.  I think that's a separate issue, but it's a good one for your to look at and solve.

**Comment by jmrundle** [comment]
PR [here](https://github.com/cooperative-computing-lab/cctools/pull/2679).

Was thinking it could also be useful to provide more flexibility with the types provided in the input file.  Currently, each parameter must match a certain JX type, otherwise an error is thrown.  However, with the new ability of expressing values as JX expressions, we may run into unavoidable type conflicts that likely should be allowed, specifically with the JX_DOUBLE and JX_INTEGER distinction.  

Example:
```
"cores": 2
"memory": 500 / cores
```
This would raise an error, since memory needs to be expressed as a JX_INTEGER, but gets parsed as a JX_DOUBLE.

This should be an easy fix, but I left it out of the PR to see what your thoughts were.

**Comment by btovar** [comment]
@jmrundle With the current implementation, cores, memory, and disk can be read as JX_DOUBLE. 
workers min and max still need to be integers at the end, but we can read them as integers and then do a ceil() on them.

**Comment by dthain** [comment]
Completed by #2679
