### ISSUE TITLE
One GPU per job

### ISSUE THREAD

**Issue by bdw2292** [cooperative-computing-lab/cctools#2666]
Hello,

With work_queue and work_queue_worker is it possible to force GPU only allocated to one task that needs gpu at a time? Multiple tasks that need gpus cannot use same gpu. I have used the --gpus on work_queue_worker and assign the task to need 1 gpu however it seems many tasks can use the same gpu.

Thanks for your time

**Comment by dthain** [comment]
Hello @bdw2292, he short story is that his should work, as long as your tasks are using CUDA and are reasonably well behaved. 

Longer story:

1 - If you start a worker normally with no options, it should observe the number of cuda-capable devices on the machine, and report that back to the manager.  (You can check that the worker is doing the right thing by looking at its output immediately after startup.)

2 - Each task that requires a GPU should indicate that with `task.specify_gpus(1)` (Python) or `work_queue_task_specify_gpus(task,1)` (C), so that the manager knows what the task wants.

3 - Each task will be assigned a distinct GPU, and the `CUDA_DEVICES` environment variable will be set to indicate which GPU it should use.  If you are writing (or using) a normal CUDA program, then the CUDA library should observe that environment variable and do the right thing.

If that's not working for you, then please tell us a little more about your setup: what sort of tasks are you running, what kind of machines, how do you start things up, etc. and we will try to help you out.

**Comment by btovar** [comment]
Brandon, 

You should get the expected behaviour with the steps have you have described. That is, use `--gpus 1` for the work_queue_worker and then `t.specify_gpus(1)` for the tasks. Let me do a quick check to make sure a new bug was not introduced recently.

That said, the worker can only keep an internal count, but cannot prevent tasks of other workers running on a machine from using the gpu.

**Comment by bdw2292** [comment]
Thanks! It works now, this essentially amounted to a bug I introduced into my wrapper where I thought I was calling task.specify_gpus(1) but in fact I was not.

Thanks again :)

**Comment by dthain** [comment]
Maybe we should have a bit in the manual that specifically highlights what to do with GPUs?

**Comment by btovar** [comment]
@bdw2292 Excellent, thanks for letting us know.

**Comment by bdw2292** [comment]
The manual is super clear, it was my fault for not realizing bug in my wrapper for work_queue. 

I am gonna start messing around with cygwin and installing from source later, curious to see if can work with windows.
