### ISSUE TITLE
wq: warn user that a task does not fit in any of the currently connected workers

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2674]
A task resource specification may preclude it to run on any of the connected workers. (E.g., task wants 2GB of memory, but workers have only 1GB). Currently the task waits forever in the queue, and a user has to investigate with `work_queue_status -A` to notice that there are tasks without workers able to run them.

It would be helpful to check, say, every 3 minutes, whether there are tasks that cannot fit a worker and print a warning.  The warning should only be printed if there are connected workers, and should show some kind of summary of the resources needed. (E.g., count of affected tasks, with maximum cores, memory, gpus, and disk requested.)

**Comment by dthain** [comment]
@cpreciad this would a good problem to start working on.  If a user sets up an application where the task doesn't match any workers, they need some good feedback to know what's happening.  (But of course, they should not get a premature or repeated alarm.)

**Comment by Cpreciad** [comment]
Possible work_queue.c functions to implement within:
ask_for_workers() : line 4156
work_queue_wait_internal: line 6261

Codebase Notes:
- a work queue task is defined in work_queue_task_create
- review in docs how a user specifies resources for a task, will help locate where I should check on worker status

**Comment by Cpreciad** [comment]
line 6261: work_queue_wait_internal 
- this function waits, but what does it wait for. does it assign tasks? 

Relevant Structs:

struct work_queue:
- contains two key members: 
hash_table *worker_table  --> table of workers;
itable *tasks                        --> maps a taskid to a task  
itable *task_state_map       --> maps taskid to state 
list *ready_list                     --> tasks ready to be sent to worker

struct work_queue_worker:
struct work_queue_resources   --> contains resources such as: cores, memory, disk info, and gpu if it has it 

Line 6301: task "t" is assigned the return value from the function task_state_any().
this looks to be the function that sends 
- task_state_any is a while loop that iterates through each key in an itable, checking whether the particular task has the desired status (in the case for work_queue_wait_internal, we want the task to return a work_queue_task struct object if its completed, else return NULL)

- TODO: where in the loop would be sufficient reason to check for the resources of  the workers? 
- feels like i should be keeping time, checking after the task_state_change function 
- need to inspect the work_queue struct further to determine the procedure of getting the resources of all available workers
- need to also determine what the client originally requested in terms of resources

**Comment by dthain** [comment]
Taking notes on what you discover is a good strategy, and also helps the rest of us to point you in the right direction.
It may be helpful to draw out a "tree" of function calls to note what calls what.

For example `work_queue_wait_internal` calls `send_one_task` in order to identify the next ready task and send it to a worker.  Have a good look at that function.

**Comment by Cpreciad** [comment]
TODO:
- figure out whether the work queue holds all workers(regardless of business or not) or if it holds only available workers
- add a flag to the work_queue_task struct
- figure out if a task has a time stamp attached to it
- find where work_queue_task struct exists
- implement notification within send_one_task

**Comment by Cpreciad** [comment]
Notes from week 4:
- Creating function that checks for task comparability. uses check_hand_against_task to iterate a task through all workers and return if a task can fit any workers at all. Should verify that this is a correct way to achieve task comparability
- now know that I can call work_queue_fill_stats to get information on the workers in the queue. 
--- Most importantly, I can use this info to get the max resources available for a worker. may be a good baseline for checking if a task can fit a worker, but need to be more thorough with checking that a task can meet all resource requirements.

**Comment by Cpreciad** [comment]
Progress week 6:
- task resource requests are stored in task->resources_requested
- currently calling check_task_compatibility within send_one_task if a particular task fails to find a worker to claim
- check_task_compatibility calls a helper function to actually determine if a task can **ever** fit to a worker. this can and probably will be fleshed out more to more accurately determine if a task can ever fit a worker. 

For Next week
- two possible courses of action for message display, flag+timer or just timer
- could implement a flag to work_queue_task that indicates if the user has been notified of a task not being able to fit to any worker
- flag will prevent the user being notified and will not run  check_task_compatibility 
- this requires me to keep track of if a task has been in the queue for more than a specified amount of time
- or maybe instead of a flag, only consider the time for tasks to be checked against. this would catch the case where a new worker joins, and the worker can actually fit the worker.

**Comment by dthain** [comment]
Fixed in #2771
