### ISSUE TITLE
Question regarding behaviour of specify_cores(0)

### ISSUE THREAD

**Issue by bdw2292** [cooperative-computing-lab/cctools#2682]
I have noticed that when I use task.specify_cores(0) that then the queue will assign the total allowed cores on that worker to this task. Was this the intended behaviour? The reason I am doing this is I have these wrappers that will submit their own quantum/molecular dynamics jobs, then they will eventually get to a point where they are just waiting for file outputs (jobs to finish) and takes up no real CPU but cctools is keeping internal count I believe. I am wondering if this is because the default cores is always 0 and then its not distinguishing between case where default is 0 and user assigns 0? I do observe however that if I set gpus needed to 1, I can then also specify cpu cores to 0. It seems to be when gpus needed is set to 0 and cpu cores set to 0 that then all cores allowed will be assigned.

Thanks for your time

**Comment by btovar** [comment]
@bdw2292, yes, this is the intended behavior.  If none of cores, gpus, memory, or disk are specified or larger than zero, then a task will use the whole worker. This is to protect against the case of sending all tasks to a single worker. (Otherwise, tasks would have no "volume", and an infinity number of tasks could run in a single worker, which can't be true.)

If you specify some resources, but set the others to zero, then wq would only take into consideration those resources that you specify when making decisions. In this case, you want to specify at least the disk space that the task use (in MB.)

Just for completeness, if you leave resources unspecified, they are divided proportionally in a worker using the value of the resources specified rounding up, unless if gpus are unspecified, which get the value of 0. This means that for cores, memory, or disk unspecified, the minimum value they will get is 1. So if a worker has 4 cores and 1000 MB of memory, and you use t.specify_memory(50) but do not specify cores, then the task would get 2 = 4*(100MB/50MB) cores.

**Comment by btovar** [comment]
Also, another case that may be relevant to you. If you specify gpus, but do not specify cores, then cores are set to zero. And as described above, gpus are always zero if unspecified.

**Comment by bdw2292** [comment]
Okay so it sounds like no matter what, I have to have at least 1 cpu core
assigned (when gpus needed are 0). Do you think there would be a way to
distinguish between user forcing cores=0 and just user not specifying
cores? This would be helpful in my case as I ran into cases where I cannot
run GPU job since all CPU cores are taken up, but sometimes they cpu cores
being taken up are just these wrappers that eventually wait for output
files and dont take any real cpu cores. I guess I would be okay if lots of
these were on same node, since its very low cpu intensive. If this is not
possible, I think I have a work around where I can specify a queue for gpu
jobs to have higher priority over a queue for cpu jobs.

I am also wondering about how I can make the queue more robust to failures.
Suppose the manager.py script dies or the control node dies, I was reading
about this "foreman mode" on work_queue_worker. Could this be used as a
"backup" queue master? Then I wouldnt want any jobs actually running on
this node so I could set the cores allowed =0 and memory=0 etc....

**Comment by btovar** [comment]
Sorry, what I meant was that you need one resource specified larger than zero, say one of disk or memory, and the rest specified as zero.  E.g., if workers report that they have 10000MB, if you t.specify_memory(50), and specify_{cores,disk,gpus}(0), you can have 200 tasks in a worker, regardless of the number of cores. However,  be cautious when doing such arrangements, as you don't want hundreds of tasks per node suddenly doing IO. (Best case your tasks run slow, worst case your sysadmin yells at you :) ).

A foreman is simply a worker to which other workers connect. It cannot do anything if manager.py dies.  wq just provides an execution engine, so you would have to build any resilience on top of that. E.g., you could keep a log of which tasks have completed, and reread this log when running manager.py again to determine which tasks can be skipped, etc.

**Comment by btovar** [comment]
Sounds good! Do let us know if things are working for you!

**Comment by bdw2292** [comment]
I'm sure they will :)

Also, this may be of interest to put on your website. I did not have luck with cygwin, there are many packages like this that have basically in complete Linux packages needed. However, its entirely possible to run an Ubuntu via docker container through windows powershell. It can even be run in background (don't have to directly interact with ubuntu) and can send commands such as work_queue_worker to Ubuntu container via docker command in powershell. I basically just followed the instructions on this website here 
https://ubuntu.com/tutorials/windows-ubuntu-hyperv-containers#1-overview

**Comment by btovar** [comment]
Thanks for the info! We will keep it in mind if somebody asks in the future.
