### ISSUE TITLE
Manager submits to worker with --gpus 1 even if gpu card suddenly dies

### ISSUE THREAD

**Issue by bdw2292** [cooperative-computing-lab/cctools#2684]
Hey,

I have noticed that the manger will submit gpu job to node with --gpus 1 even if the card suddenly dies. Is this something that could be patched?

- Brandon

**Comment by btovar** [comment]
How do you notice that gpu has failed?

The easy case would be if you can detect it when a task returns. In such case, you can block the worker, which means it is released by the manager, and since you are using --single-shot, it  will terminate. Say for example that the tasks that failed because of the gpu have exit code 123, then the main idea is to do something like this:

```python
t = q.wait(5)
if t:
    if t.return_status == 123:
        q.block_host(t.hostname)
        
        # resubmitting only works here because t is already in a final state, otherwise it is a fatal error.
        # t will get another t.id anyway.
        q.submit(t)
```

**Comment by bdw2292** [comment]
Ah that is very clever, is there a page that lists all possible error
codes? I will have to start printing them out when job fails. I typically
run "nvidia-smi" on the node and if that command fails (but I know there is
a GPU card), then I know that card has failed.

I see I have never tried resubmitting if job fails, although I did set max
retries=2, would that also give a new task id?

**Comment by dthain** [comment]
@bdw2292 can you elaborate a bit on exactly what sort of failure mode you are contemplating/observing here?

- The GPU card is present in the system but has intermittent problems, causing tasks to fail when they run.
- The GPU card fails and "disappears" from the system, so that it it was there recently, but cannot be used now.
- The GPU card burned out some long time ago but remains physically in the machine because it's not worth the trouble to remove.
- Something else?

I ask b/c there are certain categories of failures that WQ can reasonably observe and handle,  for example, exhausted memory or a dropped network connection.  And then there are other sorts of problems -- like a CPU that computes incorrect results -- that are somewhat beyond us and require application-level detection and repair.

**Comment by bdw2292** [comment]
Ah I see error code is printed in worker.debug, I will have to look for
which one occurred.

I believe this would fall under "The GPU card fails and "disappears" from
the system, so that it it was there recently, but cannot be used now" .
After rebooting the node, the card comes back fine.
