### ISSUE TITLE
Generalize Handling of /tmp in CCTools

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2973]
See https://github.com/CoffeaTeam/coffea/issues/721

In particular, condor_submit_workers uses /tmp explicitly with no way to change it.

**Comment by dthain** [comment]
@btovar I'm not sure what the meaning of "isn't available" is here.
I do see from the HTCondor error messages that the job isn't finding its files at runtime.
But beyond that, I'm not sure what the diagnosis is.  Do you have a clear picture of the problem?

**Comment by btovar** [comment]
@patrickbryant  -E "-s .."  changes the directory of the worker itself at the remote site, not of the script.

@dthain Different processes see different /tmp.

**Comment by dthain** [comment]
Hmm, does that mean each process sees a different `/tmp`, or each user, or each session...? 

In any case, it's likely we need to canvass the code base and deal with a number of `/tmp` references in a systematic way.

**Comment by btovar** [comment]
I'm not sure about that. For sure the schedd does not see the /tmp that the factory of the submit scripts create. So it could be per user, or per tree process.

**Comment by dthain** [comment]
@colinthomas-z80 here is a good first issue to work on.  In short, we have a number of places in cctools that hard-code /tmp as a location for temporary files.  This (apparently) doesn't work at Fermilab, where different services run with private /tmp namespaces.  It will probably happen in other places as well.

So, first we need a strategy for choosing /tmp location, something like this.  (@btovar may have opinions.)
- Use CCTOOLS_TEMP if set.
- Use TEMPDIR (or TEMP or TMPDIR not sure)
- Otherwise use /tmp

(@btovar we should find out what the default temp setting is at Fermilab.)

Then, find all the places in our code where /tmp comes up, and replace it with a common routine.  Keep in mind that this needs to be done a few places in the C code, and also in Python, and also in shell scripts.

**Comment by btovar** [comment]
TMPDIR is the canonical name.

**Comment by btovar** [comment]
@colinthomas-z80 As part of this issue, let's change the staging directory in work_queue.binding.py so that there is one per queue, and that the location can be chosen from the WorkQueue constructor. Right now all such directories are created in /tmp

**Comment by dthain** [comment]
@btovar we merged #3005 some time ago.  Does that close out this issue, or is there something left to be done?
