### ISSUE TITLE
wq: remotetask test hanging with osx_64

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3121]
Observed during the conda-forge CI process. I'm not quite sure why the test does not exit after the worker times out.

**Comment by btovar** [comment]
For now, I disabled the test for osx in conda-forge, as the coprocess is a tech preview of the current release. In other build modes (linux and osx arm) it works correctly.

**Comment by David-Simonetti-ND** [comment]
I think it was one of two problems. One was version of Python that one of the test machines had was pointing to Python 2.7, so when the coprocess was being started it would just die and the worker would wait forever for it come online. Another issue I remember having was that some of the machines had funky resource allocations (the OSX machines had really small resource amounts), so the coprocess would get started file, but the worker would never receive/run the task because it did not have enough resources.

**Comment by btovar** [comment]
The python comes from conda, so it should be a python3. I wonder why the worker wouldn't timeout.

**Comment by David-Simonetti-ND** [comment]
I think #3161 might fix this, it seems like there is a python that is linked to python2.7, but we want to use the python3 installed by conda. I changed the poncho_package_serverize code to explicitly insert python3 now.
