### ISSUE TITLE
Vine: Build Executor Module for Dask

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3285]
(@btovar making a note of what you are already working on.)

Build out a TaskVine executor for Dask task graphs:
https://docs.dask.org/en/stable/graphs.html

Let's to the most straightforward thing initially: each Dask task should correspond to one TaskVine task, and all of the files should be brought back to the manager as a `vine_file_local`.  Once that is working, then we can play around with some additional optimizations:
- [ ] Leave intermediate files in the cluster as `vine_file_temp`, once we have re-execution working.
- [ ] Batch together multiple Dask tasks into a single TaskVine task.
- [ ] Install Dask functions as TaskVine libraries, and invoke them via FunctionCall

**Comment by btovar** [comment]
One immediate issue for the first point is that `PythonTask` does not have a way to leave the results at the workers, it always brings the results back. We could wrap it so that the "python" result is a stub, and write the output to a tmp file at the worker. The ugly side of this is that the results cannot be used immediately in the python program.

**Comment by dthain** [comment]
Well, let's keep that in mind and burn that bridge when we get to it.
It would be more consistent if a PythonTask returned a File object which we load and then deserialize.
And then you could easily switch between file types.
But of course that sacrifices the fast case for generality.

FYI @BarrySlyDelgado

**Comment by dthain** [comment]
@BarrySlyDelgado has been working on the relative performance of Vine Futures against Disk Futures.

Please update your progress so far here
