### ISSUE TITLE
How to allocate more then one Node in makeflow in an HPC cluster 

### ISSUE THREAD

**Issue by Dcn303** [cooperative-computing-lab/cctools#3348]
Hi everyone
i am working on HPC cluster
i have 2 node with 4 core each .
How will i write a makeflow script to allocate the 4 core of both the node 1 and node 2
.I have a script simple.sh as shown below
`#! /bin/bash `
`N=8 `
`(mpirun -np $N simpleFoam -parallel) 2>&1 | tee log.simpleFoam `
`touch c`
which uses 8 mpi processes to execute
i also have to submit to slurm
i have written the makeflow script(run.makeflow) as show below
`BATCH_OPTIONS= --nodes=2 --ntasks-per-node=4`
`.MAKEFLOW MPI_PROCESS 8`
`.MAKEFLOW CORES 8`
`c : b a `
 `srun $(BATCH_OPTIONS)  ./simple.sh`
`b: a`
 `srun ./decompose.sh`
`a: `
 `srun ./blockMesh.sh`
i have submitted the makeflow to slurm as
`makeflow -T slurm run.makeflow `
the rules
`b: a`
 ` srun ./decompose.sh`
`a: `
  `srun ./blockMesh.sh` works fine and it have also allocated the two node1 and node2
but the `./simple.sh` is not executing
can anyone kindly help me on this regard

**Comment by btovar** [comment]
@Dcn303 One possible issue is that the .MAKEFLOW directives refer to the resources allocated for single rules in the makeflow file, and not to the total of resources that you have available. Since there are no nodes with 8 cores, then it is possible that makeflow is not dispatching them. Thus, one possible solution is to use:

.MAKEFLOW_MPI_PROCESS 4
.MAKEFLOW_CORES 4

Note that makeflow is not designed to run MPI executables that spawn multiple nodes. It only knows how to run one executable per node.

Also, it would be helpful if you can share the output of  `makeflow -dall -T slurm run.makeflow`

**Comment by Dcn303** [comment]
my new run.makeflow as shown below 
`BATCH_OPTIONS= -N 2 --ntasks-per-node=4`
`c: a b`
          `sbatch $(BATCH_OPTIONS) simple.sh  `
`b: a`
          `srun  ./decomposePar.sh`
`a:`
          `srun ./blockMesh.sh`
i am not sure but when i was running this i saw it running on node 1 as well as node 2 and it seems its running fiine .
my simple.sh is same as the above , let me try makeflow -dall -T slurm run.makeflow and let you know

**Comment by dthain** [comment]
Closing this out because it seems to be solved.  But let us know otherwise.

**Comment by Dcn303** [comment]
ok sir
