### ISSUE TITLE
Vine: Manager blocks when trying to communicate with busy worker.

### ISSUE THREAD

**Issue by BarrySlyDelgado** [cooperative-computing-lab/cctools#3370]
In the current iteration of TaskVine the Manager will communicate with a worker by sending input files including URLs and mini tasks to the worker. When some lull in conversation occurs the worker may  perform any necessary staging of files for a task. This includes performing mini tasks and curling URLs. If the Manager attempts to communicate with this worker while the worker is performing these side routines the Manager will block until the worker is finished and reads from the buffer. This can cause a slow startup as seen from the graph below.

One solution mentioned previously is for the worker to fork when performing mini tasks and curling URLs.
![Screenshot from 2023-06-02 14-26-44](https://github.com/cooperative-computing-lab/cctools/assets/25990259/827a1615-3616-437c-8757-cf3e55ca85d0)

**Comment by BarrySlyDelgado** [comment]
@dthain @colinthomas-z80 @tphung3 @btovar

**Comment by colinthomas-z80** [comment]
Another solution would be for the manager to track which workers have pending mini tasks, and put them in a group of least priority for subsequent task dispatches.

**Comment by dthain** [comment]
Thank you for the summary, Barry.  I would like everyone to chime in with *one* potential solution and describe the pros and cons of that solution, about one paragraph.

**Comment by btovar** [comment]
Treat minitask as regular tasks so that they can be executed asynchronously. When trying to execute a regular tasks, the worker first checks that all the needed minitasks have been executed (recursively for minitasks that depends on other minitasks).

Pros:
- Manager code does not change.
- Minitasks execute asynchronously with the same machinery that regular tasks, including monitoring.
- Minitasks shared among regular tasks are executed only once.
- Minitasks that fail get the same error handling as regular tasks.
- Manager can get exact messages for when any minitask starts and ends execution.

Cons:
- Worker logic gets more complicated.
- May need to put an upper limit on how many minitasks can execute concurrently (e.g., for a worker with hundreds of cores, we do not want hundreds of concurrent curls, or hundreds of concurrent untars).

**Comment by BarrySlyDelgado** [comment]
On the having the worker fork when staging files:

The main  benefit of this solution is that the worker can quickly fork and communicate with the manager when necessary. However, there needs to be a limit on how many processes a worker can fork at one time. For instance. if there is a task that needs 10 large files from the internet, it may not be ideal to fork 10 processes at one time. Though it would be simple to enforce a limit on theses processes. With forking there is also the possibility that the forked process exceeds its allocated resources.

**Comment by dthain** [comment]
After some discussion, I think this is the way we should go:

The core of the problem is that the worker does some things synchronously, while the manager is expecting to be able to talk to it at any point.  We should make those things asynchronous instead.

Currently, the worker keeps track of every cached object (and those not yet materialized) in `vine_cache`.  When a task is selected for execution, `vine_standbox_stagein` calls `ensure_input_file` on each input, which uses `vine_cache_ensure` to materialize that input file (if needed) and then link it into the sandbox.

Instead, we should should cause those ensure actions to happen in the background, like this:

- `vine_cache_ensure` should check to see if a file is present.  Return true if present, otherwise fork in order to carry out then necessary transfer or minitask, and return false.  (Record the process pid into the cache table.)

- New function `vine_sandbox_ensure` should call `vine_cache_ensure` on each input item  to make sure all input objects are ready.  If not, return false.

- When dispatching the next task to run, use `vine_sandbox_ensure` to determine whether it is ready or not.  Only proceed if all files are present.

- New function `vine_cache_wait` should check for completed transfer tasks (much like `handle_completed_tasks`) and mark them as done.  Call that in the worker main loop.

**Comment by dthain** [comment]
@BarrySlyDelgado post your improved graph here and declare victory!

**Comment by BarrySlyDelgado** [comment]
This has been fixed with #3391 which included asynchronous worker transfers. From the images below, we can see without the asynchronous transfers (1st image) the manager is busy transferring inputs while a worker is busy this is represented by the dark gray bar in the beginning. In the second image, this is removed with asynchronous transfers.
![TNA5](https://github.com/cooperative-computing-lab/cctools/assets/25990259/645e1c70-a79d-4929-b65b-be1f116997b3)
![TA16](https://github.com/cooperative-computing-lab/cctools/assets/25990259/fdaf6f89-3cf6-4192-8839-d4f23adac7b2)

**Comment by dthain** [comment]
Nicely done!
