### ISSUE TITLE
TaskVine: Testing for Serverless in Github CI

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#3419]
Current Github CI prevents easy changes to accomodate tests for the TaskVine serverless feature.
1. Python version in centos7 build is 3.6 while parts of poncho use features from python 3.9.
2. Several dependencies of poncho aren't available at test time (`conda-pack`, `packaging`).

The workaround in PR https://github.com/cooperative-computing-lab/cctools/pull/3418 is to simply skip the `TR_vine_function_call.sh` test. A bandage solution needs to rebuild container images to insert these new dependencies and update python versions. A good solution would use a third-party dependency management like `conda` with specific versions pinned down for quick and easy environment build. (e.g., conda install from a `spec.yml`)

**Comment by btovar** [comment]
More recent pythons might be available from the epel repository (which the current docker images already have activated). For sure I wouldn't be trying to make it work with 3.6 as it has been deprecated for a while.

**Comment by dthain** [comment]
#3421 should fix problem 2.

**Comment by dthain** [comment]
Taking a crack at problem 1 in image generation.

**Comment by dthain** [comment]
So, after poking at this for a while, I have come to the following conclusion:

- Our `centos7` build in GitHub is meant to test against the "native" rpm packages of Centos 7, so that we know what happens.  Since that platform naturally uses Python 3.6, the right thing to do here is skip the incompatible test.

- We should also have a `centos8` platform test to cover the more modern case.  That may have some other problems that need solveing.

- Since our preferred installation method for most users is via Conda, we should have a separate build platform in GitHub that installs the necessary dependencies via conda and builds that way.  (Much like the conda-forge build would work.). And that platform should give us the proper coverage of all tests.

**Comment by btovar** [comment]
For centos8 there is already almalinux8. Almalinux8 is closer to rhel8 than centos8.

**Comment by dthain** [comment]
Got it.  I'll take a crack at a generic github-conda platform to get the test coverage.

**Comment by dthain** [comment]
To summarize here:
- The various platforms currently tested in GitHub CI don't necessarily have the Python needed by the serverless code.
- Testing serverless is also quite slow, since the creation of the library requires some conda work.

I have resolved this by adding a serverless test case to cctools-packaging-test, and removed it from the quick checkin tests.
