### ISSUE TITLE
Vine: regenerate tmp files as soon as they are lost

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3496]
Currently when tmp files are lost because they worker that had them disconnected, they are regenerated only when subsequent tasks need them as input.  It would be helpful to have the option to regenerate them as soon as the worker that had them disconnected, e.g., on disconnection, check which files are tmp from the worker's table, and create the new tasks as appropriate.

The use case is topEFT and accumulation tasks.  topEFT waits for a number of tasks to be completed before creating an accumulation task. At the ramp-down, topEFT may wait some time before creating a new accumulation task, and therefore throughput is reduced, as some resources go unused when they could have been regenerating the lost results.

**Comment by dthain** [comment]
This is an interesting idea, I am pondering whether we want to make this a standard behavior or an opt-in.  If a task produces a temp file that is never consumed, then we clearly want to regenerate it quickly.  But there are other situations where it's not so obvious, either because the file is not a temporary, or needs to be consumed multiple times.
