### ISSUE TITLE
vine:  when disconnecting from a manager, workers should only preserve VINE_CACHE_ALWAYS files

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3497]
Currently they preserve everything in the cache directory. This may lead to workers running out of space when they connect to different manager through their lifetime.

**Comment by dthain** [comment]
@colinthomas-z80 please work up a short-term fix for this problem.

At the manager, `vine_file` objects are created with one of three cache levels:
```
typedef enum {
        VINE_CACHE_NEVER = 0,  /**< Do not cache file at execution site. (default) */
        VINE_CACHE = 1,        /**< File remains in cache until workflow ends. */
        VINE_CACHE_ALWAYS = 3, /**< File remains in cache until the worker teminates. **/
        VINE_PEER_NOSHARE = 4  /**< Schedule this file to be shared between peers where available. See @ref vine_enable_peer_transfers **/
} vine_file_flags_t;
```
And then based on the cache level and some other properties, `vine_file_create` will choose a cache name like this:

```
{type}-{method}-{unique}
type = file | buffer | url | temp |task
method = rnd | meta | md5-{subtype}
unique = {random characters}
```

Now, ideally, we would have the manager pass to the worker the intended cache level of each file, so that it gets a direct instruction about what to delete.  But currently, all files with status `VINE_CACHE_NEVER` and `VINE_CACHE` generate a name using the random scheme.

So, I think a short-term solution to disk space usage is this:

On worker startup (and disconnection from a master), clean the cache directory by deleting all items that look like `*-rnd-*`.  That is a bit overly aggressive (since the worker might contact the same manager a second time) but it will be safe.

Once that is working, we can ponder a longer-term solution that maybe isn't quite so aggressive.
