### ISSUE TITLE
vine: workers disconnect during normal operation

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3500]
The disconnections appear to always happen after some task is done and the manager sends unlink commands:

worker log:
```
2023/09/20 11:39:56.78 vine_worker[2890432] wq: trashing file /tmp/worker-196886-28
90432/cache/temp-rnd-pqvpqeipttqsyvx to /tmp/worker-196886-2890432/trash/ecdqwae.1695224396789685
2023/09/20 11:39:56.78 vine_worker[2890432] vine: Failed to read from manager.
2023/09/20 11:39:56.78 vine_worker[2890432] vine: disconnecting from manager 10.32.77.18:9123
2023/09/20 11:39:56.78 vine_worker[2890432] tcp: disconnected from 10.32.77.18 port 9123
```

manager log:
```
2023/09/20 11:39:55.22 vine_manager[2868795] vine: tx to earth.crc.nd.edu (10.32.77.18:26166): unlink file meta-2c66d75c0690ff56ed41dd735fb66b58
2023/09/20 11:39:55.22 vine_manager[2868795] vine: tx to earth.crc.nd.edu (10.32.77.18:26166): unlink temp-rnd-pqvpqeipttqsyvx
2023/09/20 11:39:55.22 vine_manager[2868795] tcp: disconnected from 10.32.77.18 port 26166
2023/09/20 11:39:55.22 vine_manager[2868795] vine: 0 workers connected in total now
```

This does not happen for every task, but often enough to be easy to reproduce.

**Comment by btovar** [comment]
Some more info. The unlink messages happen after the manager decided to remove the worker:

```
2023/09/20 12:45:50.21 vine_manager[2935562] vine: rx from earth.crc.nd.edu (10.32.77.18:30020): available_results
2023/09/20 12:45:50.21 vine_manager[2935562] vine: tx to earth.crc.nd.edu (10.32.77.18:30020): send_results -1
2023/09/20 12:45:50.21 vine_manager[2935562] vine: Reading result(s) from earth.crc.nd.edu (10.32.77.18:30020)
2023/09/20 12:45:55.22 vine_manager[2935562] vine: worker earth.crc.nd.edu (10.32.77.18:30020) removed
...
... unlink messages
```

which I think may only happen if the manager sees an APP_FAILURE.

**Comment by btovar** [comment]
The unlink messages happen every time a worker is removed.

**Comment by dthain** [comment]
Some things we have discovered so far:

First, the worker can be quite slow creating the sandbox for a task, when it contains a large directory tree.  This is because `file_link_recursive` is used to recreate the directory tree and hard link all of the elements in.  This should be fixed with two changes:
- [ ] `long_timeout` should be used in `vine_manager_recv_no_retry` instead of `short_timeout`, which only applies in limited situations like initial connection.
- [ ] `vine_sandbox_stagein` should just symlink in directories, rather than doing the slow recursive link.

**Comment by dthain** [comment]
Both fixed.
