### ISSUE TITLE
OpenSSL HMAC_CTX has incomplete type

### ISSUE THREAD

**Issue by sprock** [cooperative-computing-lab/cctools#3716]
Hello,

I'm working my way through the patching to get cctools to build from source on FreeBSD 13.2.  A the moment I'm stuck on this:

`COMPILE s3_file_io.o
s3_file_io.c:425:12: error: variable has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
  HMAC_CTX ctx;
           ^
/usr/local/include/openssl/ossl_typ.h:129:16: note: forward declaration of 'struct hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
s3_file_io.c:431:3: warning: implicit declaration of function 'HMAC_CTX_init' is invalid in C99 [-Wimplicit-function-declaration]
  HMAC_CTX_init(&ctx);
  ^
s3_file_io.c:435:3: warning: implicit declaration of function 'HMAC_CTX_cleanup' is invalid in C99 [-Wimplicit-function-declaration]
  HMAC_CTX_cleanup(&ctx);`

I'm building the git repo: commit 217e2004a55489219b7580dd5cdea5b562e2172a

I have tried both the system version of OpenSSL and libressl-3.8.2_1.

Thanks for any help,
Roger

**Comment by dthain** [comment]
Hello @sprock, thanks for letting us know this one.  We didn't pick this up before because this is an optional feature that wasn't compiled in our CI b/c it depends on `HAS_CURL` which wasn't included in `environment.yml`.   The code pattern here of declaring `HMAC_CTX` on the stack is deprecated, which I have fixed up in PR #3720 , let me know if that fixes the immediate issue.  (There are some other code smells in that module which I'm not touching today.). More broadly, you might have a look at `environment.yml` to either set up the build environment using Miniconda, or otherwise guide a manual setup. Cheers, Doug

**Comment by dthain** [comment]
Merged in #3720.  Thanks for the report!
