### ISSUE TITLE
[WQ] enforce memory limits

### ISSUE THREAD

**Issue by svandenhaute** [cooperative-computing-lab/cctools#3888]

**Comment by svandenhaute** [comment]
I've figured out a solution: cgroups.

In my particular case, it was especially easy. All tasks are executed within a container (apptainer or singularity), and the runtimes come with a `--memory` flag which determines the maximum amount of memory the container can use. If it gets exceeded, it will be killed 'gracefully' without affecting other running processes on the node.

I would close the issue, but perhaps this should be transformed into a discussion in order to keep it around.

**Comment by dthain** [comment]
If a container solves your problem nicely, that's great.

For situations where a container cannot be deployed, we also have the [Resource Monitor](https://cctools.readthedocs.io/en/latest/work_queue/#monitoring-and-enforcement) that can be enabled in WQ to observe, enforce, and report resource utilization.

**Comment by svandenhaute** [comment]
The container was supposed to solve the problem, but only very recent versions of `apptainer` / `singularity` are apparently capable of working with cgroups. The one on my laptop works, and does what it's supposed to do, but the two clusters that I tested it with both didn't support it.

The next thing I tried was setting `ulimit -v 1000` to e.g. restrict memory usage per process to 1MB. Unfortunately, this still leads to OOMs completely killing the `work_queue_worker`.

When enabling the resource monitor, the task still crashes the worker, instead of the worker killing the task...

**Comment by svandenhaute** [comment]
udpate: the `ulimit` attempt does appear to work now, I think.

**Comment by dthain** [comment]
Hmm, that is interesting.  In the manager log that you shared, it appears that the worker crashes in about 15 seconds.  The default measurement interval is every 5 seconds, I believe.  It may be that the application "escapes" between the measurement interval.

@btovar I don't recall whether the RM limits virtual memory, resident memory, or something else, can you fill us in?

If I recall, we didn't use `setrlimit` because it only applies to a single process, not a process tree.  Hence the need for the RM to measure every N seconds.  That said, it might still make sense for the RM (or the worker) to apply `setrlimit` since that would be effective for a single process and would provide an outer envelope in the case of multiple processes...

**Comment by svandenhaute** [comment]
In this particular case, the task is in fact `mpirun -np 32 something` so if you want me to test whether some limits actually do apply as envelope to the entire task, let me know.

**Comment by btovar** [comment]
The limits for memory in taskvine and wq are for resident memory.  The RM can limit virtual memory, but it cannot be activated through the python API (only cores, resident memory, disk, and gpus).

**Comment by dthain** [comment]
Coming back to this after a brief break and remembering a few things...

As I recall, the `ulimit -v` command corresponds to `setrlimit(RLIMIT_AS,...)` which is capable of enforcing limits on total virtual memory size.   However, it does not place any limits on the memory resident set size (RSS).  I think this is primarily because the user can control how the program allocates virtual address space, but it is the kernel's choice how much physical memory to give the process.

Now, generally, in the HPC/HTC world, we care about actual physical memory used, and don't care about virtual address space.  This is because (almost always) we want to give processes enough physical memory to run at full speed, and we don't want them swapping to virtual memory.   If a process is swapping, we (almost always) want to move it to another machine where it has enough memory.    Also, a wide variety of programs tend to allocate *far* more virtual address space than they actually used, due to garbage collection, memory mapped files, and other typical Unix tricks.

Finally, it is quite rare for a machine to reach a true kernel OOM condition, because that requires first exhausting all of physical memory and then allocating all of the disk blocks in swap.  The machine typically becomes unusably slow long before reaching that condition.

So: WorkQueue/TaskVine are focused on managing resident physical memory, not virtual address space.  And so that's what the resource monitor is intended to measure.  (And for  that matter, there is no `ulimit` capability that limits resident physical memory.)

This is all a roundabout way to ask @svandenhaute:

What is it that you actually want to limit?  Is your concern about the physical 
memory allocated to each task, or the total virtual memory space?
