### ISSUE TITLE
vine: improve disk allocation strategy, considering sandbox and cache space

### ISSUE THREAD

**Issue by colinthomas-z80** [cooperative-computing-lab/cctools#3910]
#3909 patches a bug where the worker's total disk shrinks below the allocation given to a library task. 

Ideally we would adjust the library task allocation at runtime based on the total worker disk left. How to do this exactly may be worthy of discussion.

If the worker was given the power to reduce the library task disk allocation it would trivialize any specific request made by the manager and perhaps get in the way of something carefully chosen.

However it seems like excessive work for the manager to be made responsible for monitoring the worker's remaining disk, and sending messages to the worker to reduce the library disk allocation each time the disk shrinks.

**Comment by colinthomas-z80** [comment]
One idea is to have the worker identify that the library task allocation is the same as the total disk available. It can then assume that the disk allocation is arbitrary and it is safe to reduce the task allocation along with the local disk. 

Since in this scenario there is no minimum, in the event where the whole disk is requested and actually filled up this would cause a disk overflow and worker exit which we have been trying to avoid lately.

**Comment by dthain** [comment]
I'm not understanding the problem here.  Our model of allocation assumes that the manager has a reasonable idea of what each task needs, chooses an allocation at dispatch time, and then the worker is responsible for enforcing that allocation.

This sounds like the solution to a problem:
_Ideally we would adjust the library task allocation at runtime based on the total worker disk left._ 

But I don't see yet what the problem is.

Can you explain what sequence of events leads to a problem?
