### ISSUE TITLE
Chirp Cookie Parsing

### ISSUE THREAD

**Issue by toddlmiller** [cooperative-computing-lab/cctools#591]
I'm working on supporting IPv6 better in/with HTCondor, and while I was fixing a problem with our chirp server, it occurred to me to wonder: it works for us write chirp.config files that look like this:

    ::1 12345 cookie-cookie-cookie

but I can't find a spec anywhere on what that leading host field is allowed to be.  Since our chirp server is notionally compatible with your clients (and vice versa), I thought I'd ask you.  Would it be more compatible to restrict ourselves to IPv4 addresses?

**Comment by dthain** [comment]
@batrick this bug has been stale for some time.

Do we need to fix chirp, enhance it, or something else?

**Comment by batrick** [comment]
I've been sitting on an ipv6 enhancement branch that's nearly done. I will try to polish it off in my free time this week.

**Comment by dthain** [comment]
@batrick it's not necessarily a priority to get it done this week; it can wait until after the current paper deadline.  I just wanted to get a sense of whether a solution was possible, or not.

**Comment by dthain** [comment]
Coming back to review a bug that has been open waaaay too long.

Looking at the current CCTools Chirp code, we parse the cookie file using `fscanf("%s %p %s",host,&port,cookie)`.  We merely assume that there is a space between the host and the port and don't do anything else.  So, I don't think there is any serious problem in how the config file is defined.

Now, CCTools chirp doesn't yet support IPV6.  But when we do, we need to look for the last colon in the hostport string.  

@trshaffer, please fix this as follows:

Modify `chirp_client_connect` in `chirp_client.c`.  Instead of using `sscanf` to separate the host from the port, search backwards for the last colon and (if found) use that to separate the host from the port.

That's a simple fix that addresses the chirp cookie file syntax, and the rest of IPV6 can wait for later...

**Comment by batrick** [comment]
@toddlmiller Sorry for leaving this open so long. Our current stance is that Condor's Chirp cookie file may have IPv6 addresses in the host field without any special formatting. The current whitespace delimited format of the file (thankfully) makes this simple. However, CCTools isn't yet ready for IPv6 but we're getting close with some internal branches. So any IPv6 addresses in the cookie file won't be usable with our version of Chirp. If you're okay with this temporary incompatibility, then please go ahead.
