### ISSUE TITLE
parrot mkdir/rmdir fails on SLC6

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#688]
@jblomer reports:

As for the "rm -rf ..." issue, yep, it is on a local file system.  This should be reproducible on standard Scientific Linux 6.  You can use the lhc.sh script with the bash "test case" and enter
```
    mkdir a
    touch a/b
    rm -rf a
```

**Comment by dthain** [comment]
@batrick please take a look

**Comment by batrick** [comment]
I've been looking into this using this docker image:

`https://registry.hub.docker.com/u/revive/scientific-linux/`

on this kernel:

`Linux fe625f9d545a 2.6.32-504.3.3.el6.x86_64 #1 SMP Fri Dec 12 16:05:43 EST 2014 x86_64 x86_64 x86_64 GNU/Linux`

I found some interesting problems along the way:

* Parrot segfaults if it has to delete a failed mapping. I've found and corrected that in a pending PR.
* Parrot does not correctly check the syscall return from mmap to identify an error.
* On this docker image (and perhaps others), `/dev/shm` is mounted with `noexec` preventing the channel from being used with mappings that specify `PROT_EXEC`. This is disappointing... It's possible to check for this in Parrot so I'll write up a PR for that too.

I haven't yet been able to reproduce this, otherwise. On regular RHEL 6.6, there is no problem. Running the test in Docker+SL6 to try reproducing there is how I found the above problems.
