### ISSUE TITLE
make macports for cctools

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#722]
Create a macports distribution of cctools.
First figure out how to write a portfile and test it locally.
Then, get it integrated into the macports distribution.

https://guide.macports.org/chunked/development.html

**Comment by pivie** [comment]
While I haven't done this before, this is probably up my alley if you want
me to work on it.

**Comment by dthain** [comment]
Go for it

**Comment by pivie** [comment]
I almost have this working. I have two questions:

1- It seems that "cctools" is already taken. I propose "ndcctools" as an
alternative package name. Any thoughts?

2- Macports doesn't like things in the ${prefix}/doc folder, it "violates
the layout of the ports-filesystems!". I am having a hard time fixing the
problem in the portfile, but it is probably possible with some more effort.
Is the doc folder a common approach, rather than using
${prefix}/share/doc/${package}? Or do we just do that because we don't
expect to integrate with other systems.

**Comment by btovar** [comment]
For 2, it seems in line with @hmeng-19 modifications for rpms.

**Comment by dthain** [comment]
No problem with `ndcctools` but do a little investigation (with @hmeng-19) and find a package name that is unused across rpm, macports, deb, etc so that we can pick one name and be done with it.

`share/doc` seems reasonable to me, but do it by changing the macports build procedure, not our Makefile.

**Comment by pivie** [comment]
I finally got this working. Now I just need to submit it to the official MacPorts repository. I am posting it below as a reference for anyone interested and as a backup since the file doesn't really belong in the repository. @dthain let me know if the descriptions are satisfactory.

# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4
# $Id$

PortSystem              1.0
PortGroup               github 1.0

set description_common  {Notre Dame Cooperative Computing Software}

name                    ndcctools
version                 release-4.3.4
categories              sysutils
platforms               darwin
license                 MIT
 
maintainers             nd.edu:pivie \
                        openmaintainer
                        
description             ${description_common} (cooperative-computing-lab)
long_description        ${description_common} \
                        Enable collaborators to easily harness large scale \
                        distributed systems such as clusters, clouds, and grids.
 
homepage                http://ccl.cse.nd.edu/
master_sites            https://github.com/cooperative-computing-lab/cctools/archive/
distfiles               ${version}.zip
worksrcdir              cctools-${version}

configure.pre_args      --prefix ${destroot}${prefix}

post-destroot           {
                            xinstall -d -m 755 ${destroot}${prefix}/share/doc
                            file rename -force ${destroot}${prefix}/doc ${destroot}${prefix}/share/doc/${name}

                            xinstall -d -m 755 ${destroot}${prefix}/etc/${name}
                            file rename -force ${destroot}${prefix}/etc/config.mk ${destroot}${prefix}/etc/${name}/config.mk

                        }

checksums               rmd160 7b2b1919f11f205f6452cd26aee3a6f70ff24118 \
                        sha256 17b48aa7b47ca27e6feef680ec51c9fa7a47e012a08947715f876276273a2db8
use_zip                 yes

**Comment by dthain** [comment]
Please add it to our repo under packaging/macports/cctools.port along with some instructions so that we can play around with it and keep track of it as we go..

**Comment by pivie** [comment]
As a reference the filename ends up as the following:
/opt/local/var/macports/sources/rsync.macports.org/release/tarballs/ports/sysutils/ndcctools/Portfile

**Comment by dthain** [comment]
Wow!  Make sure you document that...

**Comment by pivie** [comment]
I hate to admit defeat, but I can't find something called cctools.port in the git repo or our group AFS space. Is it on the CRC AFS or something?

However, I did submit the portfile to macports and hope to hear back in the next few days.

**Comment by btovar** [comment]
@pivie, I believe you need to create packaging/macports/ under cctools, and put your port description in the (new) file cctools.port.

**Comment by pivie** [comment]
I forgot that this is something completely new to cctools. Should the
Portfile be named cctools.port and a readme.txt be placed in the same
folder, or should cctools.port be a folder that has the Portfile in it? The
thing that makes the most sense to me is packaging/macports/Portfile and
packaging/macports/readme.txt unless there is some significance to the name
cctools.port.

**Comment by dthain** [comment]
Peter, I didn't mean to be overly specific.
What you propose makes sense to me.

**Comment by dthain** [comment]
Did you ever hear back from the macports maintainer?

**Comment by pivie** [comment]
It looks like we got hung up on the version mismatch between github and the
cctools website. I will update the port to the newest version and resubmit.

**Comment by dthain** [comment]
Based on non-response from macports, I think we have taken this as far as it is going to go...
