### ISSUE TITLE
Python utilities need to specify python2 as interpreter

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#801]
Starch for example fails if it is run on a system where `python` is Python 3.X.

**Comment by batrick** [comment]
@pbui, do you know the right way to fix this?

**Comment by pbui** [comment]
Unfortunately, there is no good way of specifying python 2.  On most distributions, `python == python2`.  On a handful, like ArchLinux, `python == python3`.  The solution is suppose to be to use `python2` or `python3`... unfortunately not all distributions have a python2 (they will have a specific `python2.6` or `python2.7`, but not `python2`).

Here is [PEP 0394](https://www.python.org/dev/peps/pep-0394/) with more information.

One way forward is to make starch with with both python2 and python3.

**Comment by batrick** [comment]
I think we have at least these options:

* Use the Python 2.X found by configure to hard code the shebang line. (similar to what we do with CCTOOLS_VERSION in our python code).
* Use something like [this](http://stackoverflow.com/a/26056481).

Whatever we end up doing, we should add Python version detection code to all of our Python code. It's unacceptable that our scripts fail once they hit an incompatibility. Instead the code should quit early if the Python version is wrong.

**Comment by btovar** [comment]
I'll take this one.

**Comment by dthain** [comment]
Two questions:

1 - Does there exist a subset of Python language that is valid in both Python 2 and Python 3?

2 - Is there any distribution other than ArchLinux that defines python=python3?  To me, that sounds like a pretty glaring backwards compatibility error.

**Comment by batrick** [comment]
> 1 - Does there exist a subset of Python language that is valid in both Python 2 and Python 3?

Peter seems to have found a subset for Starch at least. We still need to fix our other Python programs.

> 2 - Is there any distribution other than ArchLinux that defines python=python3? To me, that sounds like a pretty glaring backwards compatibility error.

Heh, Arch Linux doesn't believe in backwards compatibility (it's a rolling release distro). However, I don't think it's the only distro to do this.

**Comment by pbui** [comment]
> Peter seems to have found a subset for Starch at least. We still need to fix our other Python programs.

In general, supporting both Python 2.7 and Python 3.x is relatively straighforward.  It is supporting Python 2.4, 2.5, and 2.6 along with modern versions of Python that is difficult.  Eventually, we should cut support for RHEL5 (and thus Python 2.4) rather than doing gymnastics.

**Note**: RHEL5 has an EOL date of [March 31, 2017](https://access.redhat.com/support/policy/updates/errata)

> Heh, Arch Linux doesn't believe in backwards compatibility (it's a rolling release distro). However, I don't think it's the only distro to do this.

Arch Linux break's the mold here (ie. violates convention).  Most distributions symlink `/usr/bin/python` to `python2` as recommended in [PEP 0394](https://www.python.org/dev/peps/pep-0394/).

Distributions such as [Fedora](https://fedoraproject.org/wiki/Changes/Python_3_as_Default) and [Ubuntu](https://wiki.ubuntu.com/Python/3) are maintaining this convention.  Arch Linux is the only major mainstream distribution that I know that does not follow the `python` == `python2` convention.

**Comment by dthain** [comment]
Suppose we do this, which is a bit ugly, but makes things clear:

Create our own script `cctools-python` that takes a python version as an argument and then runs the right thing, or fails clearly.

Modify our python programs to run `#!/usr/bin/env cctools-python 2.7` so that the version expected is extremely explicit.  Then, we can decide when/how to rewrite programs as python evolves...

**Comment by btovar** [comment]
I like this idea, as we can tweak cctools-python with ./configure as needed.

**Comment by batrick** [comment]
I like the idea of creating our own interpreter but, unfortunately, we can only have one extra argument in a shebang line.

**Comment by btovar** [comment]
I do not think the extra argument is important, since we can modify cctools-python per host as needed.

Things would get ugly if the python installation changes, but we would have such problem anyway.

(Really missing perl's use v5.xx...)

**Comment by dthain** [comment]
How about we let the interpreter grep out the expected version?
```
#!/usr/bin/env cctools-python
#CCTOOLS_PYTHON_VERSION 2.7
```
I would like the code author to state explicitly what they are asking for, so that the the interpreter can cleanly state e.g. "Prune wants Python 2.7, but this machine only has Python 3.0"
