### ISSUE TITLE
Makeflow manual should document escape sequences and significant syntax differences with Make

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#918]
Celine Noirot recently encountered an issue (via cctools-nd) where quotes needed to be escaped in a recipe. The manual does not cover this.

(In fact, why do we need to escape quotes?)

**Comment by btovar** [comment]
We are parsing the command line as we parse everything else. In retrospect, this could be a bad idea.

The motivation is to have variables in makeflow work as replacement macros, so that the same name of a variable can be used in different rules with different values. In make, all the rules would use the last value defined. Now we do the replacements ala m4, but this means that quotes have special meaning for makeflow in the command line.

**Comment by btovar** [comment]
Also, we needed to find the location of > and < and parse the subsequent filenames in the same way we parsed everything else. This was needed to create symlinks with condor, but we do not do symlinks anymore.

**Comment by dthain** [comment]
The classic Make format gives us some unsolvable problems.
The new JX format gives precision and will be the way forward for these issues.
