### ISSUE TITLE
Project: Archival Form of Makeflow

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#946]
(Credit for this idea goes to Sandra Gesing.)

For the purposes of long-term archival, it may be useful to reduce a workflow to a single flattened shell script.  Add an option to makeflow that converts an input makeflow into a single output script, by adding a new visitor `dag_to_sh` to `makeflow/src/dag_visitors.c`.  See `dag_to_dot` and `dag_to_dax` for inspiration.

This feature could be used in combination with `makeflow_linker` to produce a completely self-contained package.

**Comment by dthain** [comment]
@sandragesing would you like to take a crack at this one?

**Comment by sandragesing** [comment]
Yes - I will have a look at it.

**Comment by dthain** [comment]
@trshaffer take a crack at this one too, it will be an easy proof of concept.

**Comment by sandragesing** [comment]
Hi Doug,

sorry that I did not have a look yet because of a lack of time but great
that somebody else takes a crack at it! I would be happy to see the outcome.

Thanks,
Sandra

------------------------------------------------------------------------------------------------------------
Sandra Gesing
Research Assistant Professor, Department of Computer Science and Engineering
Computational Scientist, Center for Research Computing
University of Notre Dame
http://www3.nd.edu/~sgesing
------------------------------------------------------------------------------------------------------------
